from __future__ import annotations

import argparse
import json
import subprocess
import time
from pathlib import Path

import requests

import scripts.monia_video_engine as engine

# Official Lucas French voice approved by the user.
VOICE_URL = (
    "https://marion-lucas.marionbolomey.fr/resources/monia/generated/"
    "lucas-voice-v16-b-smoother-flow-fr-candidate.wav"
)
VOICE_NAME = "lucas-voice-v16-b-smoother-flow-fr-candidate.wav"
VOICE_ID = "lucas-v16-approved"
VOICE_LINE = "Ah ouais... ça me fait plaisir que tu m'appelles juste pour ça."

SCENE_CORE = (
    "Brand-new photorealistic live video-call feed of Lucas, seen DIRECTLY THROUGH THE FRONT-FACING CAMERA OF HIS OWN SMARTPHONE. "
    "Preserve the locked Lucas identity using MonIA's Lucas canon/reference bank: early twenties, thick dark wavy hair with loose strands, strong brows, olive/tanned skin, "
    "green-hazel to gray-green eyes with a warmer amber center, short beard, youthful masculine face, canonical tattoos when naturally visible. "
    "This must be newly generated by MonIA and must NOT replay, trace, crop or reenact any supplied reference video. "
    "CRITICAL VISIO RULE: the camera viewpoint IS Lucas's smartphone front camera. Marion sees exactly this feed. "
    "NO PHONE IS VISIBLE. No mirror, no second camera, no third-person angle, no shot of Lucas holding a device. "
    "Natural arm-length selfie perspective, slightly wide smartphone front-camera geometry. Show full head, neck, shoulders and upper torso from mid-chest upward. "
    "Framing is casually human and slightly imperfect, with tiny irregular front-camera drift caused by the unseen hand outside frame. "
    "Lucas looks mainly at Marion's image on screen with occasional brief looks into the lens, creating natural screen-versus-lens gaze shifts. "
    "Subtle breathing, normal irregular blinks, tiny head movement and minute upper-body shifts. Never frozen. "
    "No cinematic grammar: no zoom, push-in, dolly, pan, rack focus, cut, montage, artificial reframing or portrait posing. "
    "SCENE CONTEXT: quiet private moment after training, soft natural late-afternoon light, muted stone and greenery in the distant background. "
    "WARDROBE: fitted charcoal training top, slightly tousled post-training hair, relaxed off-duty appearance. "
    "Natural skin texture, believable smartphone exposure, slight front-camera softness, realistic compression feel, no glamour filter, no cinematic color grade. "
    "Keep identity, wardrobe, setting, lighting and front-camera geometry coherent across every state clip. "
    "No other person, no subtitles, no UI, no text, no watermark. "
)

NEGATIVE = (
    "visible phone, smartphone in frame, hand holding phone visible, mirror selfie, reflected phone, second camera, third-person shot, "
    "camera filming Lucas holding a phone, over-the-shoulder shot, side view using phone, tripod, static studio camera, webcam framing, "
    "portrait photoshoot, presenter shot, cinematic portrait, supplied source video replay, copied motion, copied background, different man, "
    "identity drift, generic male model, altered jaw, altered nose, altered lips, altered eye color, uniformly brown eyes, bright neon green eyes, blue eyes, "
    "beauty filter, plastic skin, invented facial scar, second person, extra person, extreme close-up, face crop, full-body shot, "
    "dramatic camera motion, zoom, push-in, pan, dolly, cut, montage, reframing, frozen face, repeated mechanical gesture, "
    "cartoon, illustration, subtitles, captions, title, watermark, app UI, morphing, jitter"
)


def _download(url: str, target: Path) -> None:
    r = requests.get(url, timeout=60, headers={"Cache-Control": "no-cache"})
    r.raise_for_status()
    target.write_bytes(r.content)
    if target.stat().st_size < 4096:
        raise RuntimeError(f"Downloaded media too small: {target}")


def _probe_duration(path: Path) -> float:
    out = subprocess.check_output([
        "ffprobe", "-v", "error", "-show_entries", "format=duration",
        "-of", "default=noprint_wrappers=1:nokey=1", str(path),
    ], text=True).strip()
    value = float(out)
    if not (0.5 <= value <= 30.0):
        raise RuntimeError(f"Unexpected media duration {value:.3f}s for {path}")
    return value


def _mux(video: Path, audio: Path, output: Path) -> None:
    subprocess.run([
        "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
        "-i", str(video), "-i", str(audio),
        "-map", "0:v:0", "-map", "1:a:0",
        "-c:v", "copy", "-c:a", "aac", "-b:a", "192k",
        "-shortest", "-movflags", "+faststart", str(output),
    ], check=True)


def _run_compute(profile: engine.CharacterProfile, source: Path, target: Path) -> str:
    errors: list[str] = []
    for attempt in range(1, 4):
        target.unlink(missing_ok=True)
        try:
            return engine._run_ltx(profile, source, target)
        except Exception as exc:
            errors.append(f"LTX attempt {attempt}: {exc}")
            if attempt < 3:
                time.sleep(18 * attempt)
    target.unlink(missing_ok=True)
    try:
        return engine._run_wan(profile, source, target)
    except Exception as exc:
        errors.append(f"WAN fallback: {exc}")
        raise RuntimeError("No MonIA video compute available: " + " | ".join(errors)) from exc


def _prepare_voice() -> tuple[Path, float]:
    voice = engine.WORK_DIR / VOICE_NAME
    if not voice.exists():
        _download(VOICE_URL, voice)
    return voice, _probe_duration(voice)


def _state_specs(speech_duration: float) -> dict[str, dict[str, object]]:
    visual_duration = max(4, min(12, int(round(speech_duration + 0.35))))
    return {
        "listening": {
            "duration": 5,
            "output": "visio-lucas-surprise-v5-monia-listening-candidate.mp4",
            "prompt": SCENE_CORE + (
                "STATE LISTENING. Marion is speaking. Lucas remains silent and attentive in the live front-camera feed. "
                "He breathes naturally, blinks irregularly, makes one tiny unseen-hand framing correction, briefly checks Marion's image on screen, "
                "then returns his eyes toward the lens and gives a very small acknowledging head movement. Mouth mostly closed."
            ),
        },
        "speaking": {
            "duration": visual_duration,
            "output": "visio-lucas-surprise-v5-monia-speaking-v16-candidate.mp4",
            "silent": "visio-lucas-surprise-v5-monia-speaking-silent-candidate.mp4",
            "prompt": SCENE_CORE + (
                f"STATE SPEAKING. Lucas speaks exactly this approved French line: '{VOICE_LINE}' "
                f"The final audio is the locked {VOICE_ID} performance and lasts about {speech_duration:.2f} seconds. "
                "Shape the visible speech performance around that exact utterance: connected French phrasing, one natural hesitation after 'ouais', "
                "warm private-call energy, tiny irregular head motion, normal blinks, restrained affectionate expression. "
                "Do not invent extra words. Do not make Lucas continue moving his lips after the final phrase. "
                "No whisper, no dreamy slow delivery, no presenter/commercial acting, no exaggerated mouth shapes."
            ),
        },
        "reaction": {
            "duration": 4,
            "output": "visio-lucas-surprise-v5-monia-reaction-candidate.mp4",
            "prompt": SCENE_CORE + (
                "STATE REACTION. Lucas has just finished speaking and listens to Marion. "
                "He gives a tiny amused breath, slight eyebrow movement and faint half-smile, then settles back to attentive neutral. "
                "One very subtle front-camera drift keeps the live-call feeling believable. No speaking."
            ),
        },
    }


def _validate_av_sync(video: Path, voice_duration: float) -> dict[str, float]:
    video_duration = _probe_duration(video)
    delta = abs(video_duration - voice_duration)
    # This is a coarse container-level gate, not phoneme-level lip-sync validation.
    if delta > 0.9:
        raise RuntimeError(
            f"Speaking candidate rejected: A/V duration mismatch {delta:.3f}s "
            f"(video={video_duration:.3f}s voice={voice_duration:.3f}s)"
        )
    return {"video_duration": video_duration, "voice_duration": voice_duration, "duration_delta": delta}


def _generate_state(state: str, specs: dict[str, dict[str, object]], voice: Path, voice_duration: float) -> tuple[Path, str, dict[str, float] | None]:
    spec = specs[state]
    silent_name = str(spec.get("silent", spec["output"]))
    profile = engine.CharacterProfile(
        key=f"lucas-visio-surprise-v5-monia-{state}",
        canon_url=f"{engine.SITE}/resources/monia/canon/lucas/reference.jpg",
        prompt=str(spec["prompt"]),
        negative=NEGATIVE,
        width=576,
        height=1024,
        aspect_ratio="9:16 (Portrait)",
        duration=int(spec["duration"]),
        output_name=silent_name,
    )
    source = engine.WORK_DIR / "lucas-visio-surprise-v5-canon.png"
    silent = engine.WORK_DIR / silent_name
    engine._download_canon(profile, source)
    provider = _run_compute(profile, source, silent)

    if state != "speaking":
        return silent, provider, None

    final = engine.WORK_DIR / str(spec["output"])
    final.unlink(missing_ok=True)
    _mux(silent, voice, final)
    metrics = _validate_av_sync(final, voice_duration)
    return final, provider, metrics


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate MonIA-owned true front-camera Lucas surprise visio with locked V16 voice")
    parser.add_argument("--publish-candidate", action="store_true")
    parser.add_argument("--state", choices=["listening", "speaking", "reaction", "all"], default="all")
    args = parser.parse_args()

    voice, voice_duration = _prepare_voice()
    specs = _state_specs(voice_duration)
    states = list(specs) if args.state == "all" else [args.state]
    failures: list[str] = []

    manifest = {
        "pipeline": "monia-surprise-visio-v5",
        "voice_id": VOICE_ID,
        "voice_file": VOICE_NAME,
        "voice_line": VOICE_LINE,
        "voice_duration": voice_duration,
        "camera": "true-smartphone-front-camera",
        "candidate_only": True,
        "phoneme_sync_validated": False,
        "states": {},
    }

    for state in states:
        try:
            path, provider, metrics = _generate_state(state, specs, voice, voice_duration)
            if not path.exists() or path.stat().st_size < 10000:
                raise RuntimeError(f"Invalid generated state: {state}")
            manifest["states"][state] = {
                "provider": provider,
                "output": path.name,
                "bytes": path.stat().st_size,
                "metrics": metrics,
            }
            print(f"MONIA_VISIO_SURPRISE_V5 state={state} compute={provider} output={path} bytes={path.stat().st_size}")
            if args.publish_candidate:
                url = engine.publish_candidate(path)
                manifest["states"][state]["candidate_url"] = url
                print(f"MONIA_VISIO_SURPRISE_V5_CANDIDATE state={state} url={url}")
        except Exception as exc:
            failures.append(f"{state}: {exc}")
            print(f"MONIA_VISIO_SURPRISE_V5_FAILED state={state} error={exc}")
            if args.state != "all":
                raise

    manifest_path = engine.WORK_DIR / "monia-surprise-visio-v5-manifest.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"MONIA_VISIO_SURPRISE_V5_MANIFEST {manifest_path}")

    if failures:
        raise RuntimeError("Some MonIA surprise visio V5 states failed: " + " | ".join(failures))


if __name__ == "__main__":
    main()
