import {getLifeAgeSnapshot,MARION_BIRTHDAY,LUCAS_BIRTHDAY,isMarionBirthday,isLucasBirthday} from './life-age-engine';

const SAVE_KEY='marion-lucas-save-v4';
type Target='marion'|'lucas';
type CalendarItem={owner:'Marion'|'Lucas'|'Nous';title:string;day:number;note:string;time?:string;place?:string};
type LucasSurpriseKind='gift'|'dinner'|'outing'|'escape'|'quiet-moment'|'family-moment';
type LucasBirthdaySurprise={birthdayDay:number;plannedDay:number;kind:LucasSurpriseKind;status:'planned'|'revealed'|'completed';professionalConflict:boolean;seed:number;};
type Save={day?:number;time?:string;place?:string;metLucas?:boolean;official?:boolean;relationship?:number;trust?:number;children?:number;calendar?:CalendarItem[];eventHistory?:string[];memories?:string[];flags?:Record<string,unknown>;updatedAt?:number};
export type BirthdaySnapshot={day:number;lifeYear:number;today:Target[];next:{target:Target;day:number;daysUntil:number;label:string}[];lucasSurprise:{planned:boolean;availableToday:boolean;revealed:boolean;kind?:LucasSurpriseKind}|null;canonical:true};

function read():Save|null{try{const raw=localStorage.getItem(SAVE_KEY);return raw?JSON.parse(raw) as Save:null}catch{return null}}
function write(s:Save){s.updatedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('monia:save-changed',{detail:{key:SAVE_KEY}}));window.dispatchEvent(new CustomEvent('monia:birthday-changed'));return true}
function n(v:unknown,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function clamp(v:number){return Math.max(0,Math.min(100,Math.round(v)))}
function hash(v:string){let h=2166136261;for(let i=0;i<v.length;i++){h^=v.charCodeAt(i);h=Math.imul(h,16777619)}return Math.abs(h>>>0)}
function annualDay(lifeYear:number,dayOfYear:number){return(Math.max(1,lifeYear)-1)*365+dayOfYear}
function nextBirthdayDay(currentDay:number,birthdayDayOfYear:number){const year=Math.floor((Math.max(1,currentDay)-1)/365)+1;const thisYear=annualDay(year,birthdayDayOfYear);return thisYear>=currentDay?thisYear:annualDay(year+1,birthdayDayOfYear)}
function ensureCalendarItem(s:Save,item:CalendarItem){if(!Array.isArray(s.calendar))s.calendar=[];if(s.calendar.some(x=>x.day===item.day&&x.title===item.title))return false;s.calendar.push(item);return true}
function addHistory(s:Save,event:string){const h=Array.isArray(s.eventHistory)?s.eventHistory:[];if(!h.includes(event))h.push(event);s.eventHistory=h.slice(-420)}
function addMemory(s:Save,text:string){const m=Array.isArray(s.memories)?s.memories:[];if(!m.includes(text))m.unshift(text);s.memories=m.slice(0,80)}
function flags(s:Save){return s.flags||(s.flags={})}
function lucasBusyOn(s:Save,day:number){return(s.calendar||[]).some(i=>i.day===day&&i.owner==='Lucas'&&/corrida|novillada|feria|arène|arena|plaza|entraîn|entrain|tentadero|voyage|train|avion|déplacement|deplacement|presse|interview|tournage|apoderado|cuadrilla|réunion|reunion/i.test(`${i.title} ${i.note} ${i.place||''}`))}
function readLucasSurprise(s:Save):LucasBirthdaySurprise|null{const v=flags(s).lucasMarionBirthdaySurprise;if(!v||typeof v!=='object'||Array.isArray(v))return null;const x=v as Partial<LucasBirthdaySurprise>;if(!Number.isFinite(Number(x.birthdayDay))||!Number.isFinite(Number(x.plannedDay)))return null;if(!['gift','dinner','outing','escape','quiet-moment','family-moment'].includes(String(x.kind)))return null;if(!['planned','revealed','completed'].includes(String(x.status)))return null;return x as LucasBirthdaySurprise}
function chooseLucasSurprise(s:Save,birthdayDay:number):LucasBirthdaySurpriseKind{const relationship=n(s.relationship,0),trust=n(s.trust,0),children=Math.max(0,Math.floor(n(s.children,0))),busy=lucasBusyOn(s,birthdayDay),seed=hash(`lucas-birthday:${birthdayDay}:${relationship}:${trust}:${children}`);if(busy)return relationship>=65?'dinner':'gift';if(children>0&&relationship>=75&&seed%5===0)return'family-moment';if(relationship>=82&&trust>=70&&seed%6===0)return'escape';if(relationship>=68)return(['dinner','outing','gift','quiet-moment'] as LucasSurpriseKind[])[seed%4];return seed%2===0?'gift':'quiet-moment'}
function surpriseLabel(kind:LucasSurpriseKind){return kind==='gift'?'un cadeau préparé par Lucas':kind==='dinner'?'un dîner préparé par Lucas':kind==='outing'?'une sortie surprise préparée par Lucas':kind==='escape'?'une escapade surprise préparée par Lucas':kind==='family-moment'?'un moment familial préparé par Lucas':'un moment à deux préparé par Lucas'}

export function ensureBirthdayCalendar(){const s=read();if(!s)return false;const lifeYear=getLifeAgeSnapshot(s).lifeYear;let changed=false;changed=ensureCalendarItem(s,{owner:'Marion',title:'Anniversaire de Marion',day:annualDay(lifeYear,MARION_BIRTHDAY.dayOfYear),note:'4 juillet · journée anniversaire'})||changed;changed=ensureCalendarItem(s,{owner:'Lucas',title:'Anniversaire de Lucas',day:annualDay(lifeYear,LUCAS_BIRTHDAY.dayOfYear),note:'3 octobre · journée anniversaire'})||changed;if(changed)write(s);return changed}

export function ensureLucasMarionBirthdaySurprise(){const s=read();if(!s||!s.metLucas)return false;const day=Math.max(1,n(s.day,1)),birthdayDay=nextBirthdayDay(day,MARION_BIRTHDAY.dayOfYear),daysUntil=birthdayDay-day;const existing=readLucasSurprise(s);if(existing?.birthdayDay===birthdayDay)return false;if(daysUntil<0||daysUntil>14)return false;const relationship=n(s.relationship,0);if(relationship<28)return false;const seed=hash(`lucas-plan:${birthdayDay}:${relationship}:${n(s.trust,0)}`);const planningLead=3+(seed%8);if(daysUntil>planningLead)return false;const surprise:LucasBirthdaySurprise={birthdayDay,plannedDay:day,kind:chooseLucasSurprise(s,birthdayDay),status:'planned',professionalConflict:lucasBusyOn(s,birthdayDay),seed};flags(s).lucasMarionBirthdaySurprise=surprise;addHistory(s,`lucas-birthday-surprise-planned:${birthdayDay}`);return write(s)}

export function getBirthdaySnapshot():BirthdaySnapshot|null{const s=read();if(!s)return null;const ages=getLifeAgeSnapshot(s),day=ages.day;const today:Target[]=[];if(isMarionBirthday(day))today.push('marion');if(isLucasBirthday(day))today.push('lucas');const marionDay=nextBirthdayDay(day,MARION_BIRTHDAY.dayOfYear),lucasDay=nextBirthdayDay(day,LUCAS_BIRTHDAY.dayOfYear),surprise=readLucasSurprise(s);return{day,lifeYear:ages.lifeYear,today,next:[{target:'marion',day:marionDay,daysUntil:marionDay-day,label:MARION_BIRTHDAY.label},{target:'lucas',day:lucasDay,daysUntil:lucasDay-day,label:LUCAS_BIRTHDAY.label}].sort((a,b)=>a.daysUntil-b.daysUntil),lucasSurprise:surprise?{planned:true,availableToday:surprise.birthdayDay===day,revealed:surprise.status!=='planned',kind:surprise.status==='planned'?undefined:surprise.kind}:null,canonical:true}}

export function revealLucasBirthdaySurprise(){const s=read();if(!s||!isMarionBirthday(Math.max(1,n(s.day,1))))return null;const surprise=readLucasSurprise(s);if(!surprise||surprise.birthdayDay!==Math.max(1,n(s.day,1)))return null;if(surprise.status==='planned'){surprise.status='revealed';flags(s).lucasMarionBirthdaySurprise=surprise;addHistory(s,`lucas-birthday-surprise-revealed:${surprise.birthdayDay}:${surprise.kind}`);write(s)}return{kind:surprise.kind,label:surpriseLabel(surprise.kind),professionalConflict:surprise.professionalConflict}}

export function completeLucasBirthdaySurprise(){const s=read();if(!s||!isMarionBirthday(Math.max(1,n(s.day,1))))return false;const surprise=readLucasSurprise(s);if(!surprise||surprise.birthdayDay!==Math.max(1,n(s.day,1))||surprise.status==='completed')return false;surprise.status='completed';flags(s).lucasMarionBirthdaySurprise=surprise;addHistory(s,`lucas-birthday-surprise-completed:${surprise.birthdayDay}:${surprise.kind}`);addMemory(s,`Lucas avait préparé ${surpriseLabel(surprise.kind)} pour l’anniversaire de Marion.`);s.relationship=clamp(n(s.relationship,0)+2);s.trust=clamp(n(s.trust,0)+1);return write(s)}

export function planBirthdayEvent(target:Target,title:string){const s=read();if(!s||!title.trim())return false;const day=Math.max(1,n(s.day,1));const birthdayDay=nextBirthdayDay(day,target==='marion'?MARION_BIRTHDAY.dayOfYear:LUCAS_BIRTHDAY.dayOfYear);const owner:CalendarItem['owner']=target==='marion'?'Marion':'Lucas';const clean=title.trim();if(!Array.isArray(s.calendar))s.calendar=[];if(s.calendar.some(x=>x.day===birthdayDay&&x.title===clean))return false;s.calendar.push({owner,title:clean,day:birthdayDay,note:`Prévu pour l’anniversaire du ${target==='marion'?MARION_BIRTHDAY.label:LUCAS_BIRTHDAY.label}.`});addHistory(s,`birthday-plan:${target}:${birthdayDay}:${clean.toLowerCase().replace(/\s+/g,'-').slice(0,40)}`);return write(s)}

export function offerBirthdayGift(target:Target,gift:string){const s=read();if(!s||!gift.trim())return false;const day=Math.max(1,n(s.day,1));if(target==='marion'&&!isMarionBirthday(day))return false;if(target==='lucas'&&!isLucasBirthday(day))return false;if(target==='lucas'&&!s.metLucas)return false;const clean=gift.trim();const key=`birthday-gift:${target}:${day}:${clean.toLowerCase().replace(/\s+/g,'-').slice(0,40)}`;if((s.eventHistory||[]).includes(key))return false;addHistory(s,key);if(target==='lucas'){s.relationship=clamp(n(s.relationship,0)+2);s.trust=clamp(n(s.trust,0)+1);addMemory(s,`Marion a offert ${clean} à Lucas pour son anniversaire.`)}else{addMemory(s,`Marion a reçu ${clean} pour son anniversaire.`)}return write(s)}

function refresh(){window.setTimeout(()=>{try{ensureBirthdayCalendar();ensureLucasMarionBirthdaySurprise()}catch{}},0)}
window.setTimeout(refresh,1400);window.addEventListener('marion:statechange',refresh as EventListener);window.addEventListener('monia:save-changed',refresh as EventListener);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});

declare global{interface Window{__moniaBirthdays?:()=>BirthdaySnapshot|null;__moniaPlanBirthdayEvent?:(target:Target,title:string)=>boolean;__moniaOfferBirthdayGift?:(target:Target,gift:string)=>boolean;__moniaEnsureBirthdayCalendar?:()=>boolean;__moniaEnsureLucasBirthdaySurprise?:()=>boolean;__moniaRevealLucasBirthdaySurprise?:()=>{kind:LucasSurpriseKind;label:string;professionalConflict:boolean}|null;__moniaCompleteLucasBirthdaySurprise?:()=>boolean}}
window.__moniaBirthdays=getBirthdaySnapshot;window.__moniaPlanBirthdayEvent=planBirthdayEvent;window.__moniaOfferBirthdayGift=offerBirthdayGift;window.__moniaEnsureBirthdayCalendar=ensureBirthdayCalendar;window.__moniaEnsureLucasBirthdaySurprise=ensureLucasMarionBirthdaySurprise;window.__moniaRevealLucasBirthdaySurprise=revealLucasBirthdaySurprise;window.__moniaCompleteLucasBirthdaySurprise=completeLucasBirthdaySurprise;
