import './iphone-conversations.css';

const SAVE_KEY='marion-lucas-save-v4';

type Message={from:string;text:string;day:number;read:boolean;to?:string;contact?:string;id?:string};
type Save={day?:number;time?:string;metLucas?:boolean;phoneUnread?:number;messages?:Message[];flags?:Record<string,unknown>};

function read():Save|null{try{const raw=localStorage.getItem(SAVE_KEY);return raw?JSON.parse(raw) as Save:null}catch{return null}}
function write(s:Save){try{localStorage.setItem(SAVE_KEY,JSON.stringify(s));window.dispatchEvent(new StorageEvent('storage',{key:SAVE_KEY,newValue:JSON.stringify(s)}))}catch{}}
function esc(v:string){return v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]||c))}
function key(v:string){return v.trim().toLowerCase()}
function contactFor(m:Message,s:Save){if(m.from&&m.from!=='Toi')return m.from;if(m.to)return m.to;if(m.contact)return m.contact;return s.metLucas?'Lucas':'Marine'}
function contacts(s:Save){const names=new Set<string>();for(const m of s.messages||[]){const c=contactFor(m,s);if(c&&c!=='Toi')names.add(c)}if(s.metLucas)names.add('Lucas');return [...names]}
function unreadFor(s:Save,contact:string){return (s.messages||[]).filter(m=>m.from===contact&&m.read===false).length}
function lastFor(s:Save,contact:string){return (s.messages||[]).find(m=>key(contactFor(m,s))===key(contact))||null}
function recomputeUnread(s:Save){s.phoneUnread=(s.messages||[]).filter(m=>m.from!=='Toi'&&m.read===false).length}
function activeContact(s:Save){const f=s.flags||(s.flags={});const stored=String(f.iphoneActiveContact||'');if(stored)return stored;const unread=(s.messages||[]).find(m=>m.from!=='Toi'&&m.read===false);return unread?.from||contacts(s)[0]||''}
function setActive(s:Save,contact:string){const f=s.flags||(s.flags={});f.iphoneActiveContact=contact;write(s)}
function isMessagesScreen(phone:HTMLElement){const content=phone.querySelector('#phoneContent');if(!content)return false;const txt=(content.textContent||'').toLowerCase();return txt.includes('messages')||!!content.querySelector('.smsThread,.iphoneConversationList,.iphoneConversationThread')}
function latestText(m:Message|null){if(!m)return'Aucun message pour le moment.';const t=m.text.replace(/^\[\[(?:voice|photo):|\]\]$/g,'').trim();return t.length>66?`${t.slice(0,63)}…`:t}

function listHTML(s:Save){const rows=contacts(s).map(contact=>{const last=lastFor(s,contact),unread=unreadFor(s,contact);return`<button class="iphoneConversationRow ${unread?'hasUnread':''}" data-iphone-contact="${esc(contact)}"><span class="iphoneContactAvatar">${esc(contact.slice(0,1).toUpperCase())}</span><span class="iphoneConversationText"><strong>${esc(contact)}</strong><em>${esc(latestText(last))}</em></span>${unread?`<i>${unread}</i>`:''}</button>`}).join('');return`<div class="iphoneConversationList"><header><strong>Messages</strong><small>${Number(s.phoneUnread||0)>0?`${s.phoneUnread} non lu${Number(s.phoneUnread)>1?'s':''}`:'À jour'}</small></header>${rows||'<p class="iphoneEmptyMessages">Tes conversations apparaîtront ici.</p>'}</div>`}
function threadMessages(s:Save,contact:string){return (s.messages||[]).filter(m=>key(contactFor(m,s))===key(contact)).slice().reverse()}
function body(text:string){if(text.startsWith('[[voice:'))return`<span class="iphoneVoicePlaceholder">Note vocale</span>`;if(text.startsWith('[[photo:'))return`<span class="iphonePhotoPlaceholder">Photo</span>`;return esc(text)}
function threadHTML(s:Save,contact:string){const msgs=threadMessages(s,contact).map(m=>`<article class="iphoneThreadBubble ${m.from==='Toi'?'mine':'theirs'}"><p>${body(m.text)}</p><small>Jour ${m.day}</small></article>`).join('');const marineInvite=contact==='Marine'&&Number(s.day||1)===1&&!s.flags?.marineDay1Reply;const quick=marineInvite?`<div class="iphoneContactQuick"><button data-marine-quick="J'arrive, je te rejoins aux arènes.">J’arrive</button><button data-marine-quick="Je te rejoins un peu plus tard.">Un peu plus tard</button><button data-marine-quick="Pas ce matin, je te redis après.">Pas ce matin</button></div>`:'';const actions=contact==='Lucas'&&s.metLucas?`<div class="iphoneThreadActions"><button data-iphone-lucas-call="audio">Appel</button><button data-iphone-lucas-call="video">Visio</button></div>`:'';return`<div class="iphoneConversationThread"><header><button data-iphone-back>‹</button><div><strong>${esc(contact)}</strong><small>Messages</small></div>${actions}</header><div class="iphoneThreadScroll">${msgs||'<p class="iphoneEmptyMessages">Aucun message.</p>'}</div>${quick}<form class="iphoneContactComposer"><textarea maxlength="280" rows="1" placeholder="Écrire à ${esc(contact)}…"></textarea><button type="submit" aria-label="Envoyer">↑</button></form></div>`}

function markContactRead(s:Save,contact:string){for(const m of s.messages||[])if(m.from===contact)m.read=true;recomputeUnread(s);setActive(s,contact)}
function renderList(phone:HTMLElement){const s=read();const c=phone.querySelector<HTMLElement>('#phoneContent');if(!s||!c)return;c.innerHTML=listHTML(s);phone.classList.remove('iphoneConversation');}
function renderThread(phone:HTMLElement,contact:string){const s=read();const c=phone.querySelector<HTMLElement>('#phoneContent');if(!s||!c)return;markContactRead(s,contact);c.innerHTML=threadHTML(s,contact);phone.classList.add('iphoneConversation');requestAnimationFrame(()=>{const sc=c.querySelector<HTMLElement>('.iphoneThreadScroll');if(sc)sc.scrollTop=sc.scrollHeight});}
function send(contact:string,text:string){const s=read();if(!s)return;const clean=text.trim().slice(0,280);if(!clean)return;const messages=s.messages||(s.messages=[]);messages.unshift({from:'Toi',to:contact,contact,text:clean,day:Number(s.day||1),read:true,id:`msg-${Date.now()}`});const f=s.flags||(s.flags={});f.iphoneActiveContact=contact;if(contact==='Marine'&&Number(s.day||1)===1){f.marineDay1Reply=clean;const lower=clean.toLowerCase();f.marineDay1Plan=/arriv|rejoi|viens|café|cafe|arène|arene/.test(lower)?'meet':/plus tard|après|apres/.test(lower)?'later':'decline';window.dispatchEvent(new CustomEvent('monia:marine-day1-reply',{detail:{text:clean,plan:f.marineDay1Plan}}));}write(s)}
function openContactFromLatestUnread(phone:HTMLElement){const s=read();if(!s)return false;const unread=(s.messages||[]).find(m=>m.from!=='Toi'&&m.read===false);if(!unread)return false;renderThread(phone,unread.from);return true}

function enhance(phone:HTMLElement){if(!isMessagesScreen(phone))return;const content=phone.querySelector<HTMLElement>('#phoneContent');if(!content)return;if(content.querySelector('.iphoneConversationList,.iphoneConversationThread'))return;renderList(phone)}

document.addEventListener('click',e=>{const t=e.target as HTMLElement|null;if(!t)return;const phone=t.closest<HTMLElement>('.phoneDevice.iphoneReal');if(!phone)return;const app=t.closest<HTMLElement>('[data-phoneapp="messages"],.iphoneAppMessages');if(app){window.setTimeout(()=>renderList(phone),40);return}const row=t.closest<HTMLElement>('[data-iphone-contact]');if(row){e.preventDefault();e.stopPropagation();renderThread(phone,String(row.dataset.iphoneContact||''));return}if(t.closest('[data-iphone-back]')){e.preventDefault();e.stopPropagation();renderList(phone);return}const quick=t.closest<HTMLElement>('[data-marine-quick]');if(quick){e.preventDefault();e.stopPropagation();const text=String(quick.dataset.marineQuick||'');send('Marine',text);renderThread(phone,'Marine');return}const call=t.closest<HTMLElement>('[data-iphone-lucas-call]');if(call){e.preventDefault();e.stopPropagation();const video=call.dataset.iphoneLucasCall==='video';window.dispatchEvent(new CustomEvent('monia:daily-intent',{detail:{intent:'open-phone-lucas',source:'conversation',video}}));return}},true);

document.addEventListener('submit',e=>{const form=(e.target as HTMLElement).closest<HTMLFormElement>('.iphoneContactComposer');if(!form)return;e.preventDefault();const phone=form.closest<HTMLElement>('.phoneDevice.iphoneReal');const s=read();if(!phone||!s)return;const contact=activeContact(s);const input=form.querySelector<HTMLTextAreaElement>('textarea');const text=input?.value||'';send(contact,text);renderThread(phone,contact)},true);

window.addEventListener('monia:open-latest-thread',()=>{const phone=document.querySelector<HTMLElement>('.phoneDevice.iphoneReal');if(phone)openContactFromLatestUnread(phone)});
const observer=new MutationObserver(()=>document.querySelectorAll<HTMLElement>('.phoneDevice.iphoneReal').forEach(enhance));observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('storage',()=>document.querySelectorAll<HTMLElement>('.phoneDevice.iphoneReal').forEach(phone=>{if(phone.querySelector('.iphoneConversationThread')){const s=read();if(s)renderThread(phone,activeContact(s))}else enhance(phone)}));

declare global{interface Window{__moniaOpenPhoneContact?:(contact:string)=>boolean}}
window.__moniaOpenPhoneContact=(contact:string)=>{const phone=document.querySelector<HTMLElement>('.phoneDevice.iphoneReal');if(!phone)return false;renderThread(phone,contact);return true};
