import {approvedLucasVisioFor,hasApprovedLucasVisio} from './approved-visio-runtime';
import {readGameplayVisioTicket} from './gameplay-visio-director';

const OVERLAY_ID='moniaVisioOverlay';
type LiveState='connecting'|'listening'|'thinking'|'speaking'|'reaction'|'media-error';
type SpeechDetail={type?:'start'|'boundary'|'end'|'error'|'thinking'};

let forcedState:LiveState|null=null;
let reactionTimer=0;

function ensureStatus(overlay:HTMLElement){let badge=overlay.querySelector<HTMLElement>('[data-monia-live-state]');if(badge)return badge;badge=document.createElement('div');badge.dataset.moniaLiveState='connecting';badge.style.cssText='position:absolute;z-index:4;top:88px;left:24px;padding:7px 11px;border-radius:999px;background:rgba(0,0,0,.48);backdrop-filter:blur(9px);font:600 12px/1.2 system-ui,sans-serif;letter-spacing:.03em;color:#fff;border:1px solid rgba(255,255,255,.15)';overlay.appendChild(badge);return badge}
function setState(overlay:HTMLElement,state:LiveState,cameraOff=false){const badge=ensureStatus(overlay);badge.dataset.moniaLiveState=state;const label=state==='connecting'?'Connexion…':state==='speaking'?'Dominic parle':state==='reaction'?'Dominic réagit':state==='thinking'?'Dominic réfléchit':state==='listening'?'Dominic écoute':'Vidéo indisponible';badge.textContent=`● ${label}${cameraOff&&state!=='connecting'?' · caméra coupée':''}`}
function approvedUrl(state:LiveState){if(state==='speaking')return approvedLucasVisioFor('talk')?.src||'';if(state==='reaction')return approvedLucasVisioFor('reaction')?.src||approvedLucasVisioFor('listen')?.src||'';if(state==='thinking')return approvedLucasVisioFor('listen')?.src||'';if(state==='listening')return approvedLucasVisioFor('listen')?.src||'';return''}
function transientUrl(state:LiveState){const ticket=readGameplayVisioTicket();if(ticket?.source!=='monia-transient-candidate')return'';const media=ticket.stateMedia||{};if(state==='speaking')return media.speaking||'';if(state==='reaction')return media.reaction||media.listening||'';if(state==='thinking')return media.thinking||media.listening||'';if(state==='listening')return media.listening||ticket.videoUrl||'';return''}
function stateUrl(state:LiveState){return transientUrl(state)||approvedUrl(state)}
function clearNeutral(overlay:HTMLElement){overlay.querySelector('#moniaVisioNeutral')?.remove()}
function installVideo(overlay:HTMLElement,url:string,state:LiveState){if(!url)return null;clearNeutral(overlay);const existing=overlay.querySelector<HTMLVideoElement>('#moniaVisioVideo')||overlay.querySelector<HTMLVideoElement>('.iphoneApprovedVisioVideo');const transient=Boolean(transientUrl(state));if(existing){const absolute=new URL(url,location.href).href;if(existing.src!==absolute){existing.style.opacity='.55';existing.src=url;existing.load()}existing.id='moniaVisioVideo';existing.dataset.moniaVisualState=state;existing.playbackRate=1;existing.muted=!transient||state!=='speaking';void existing.play().catch(()=>{existing.muted=true;void existing.play().catch(()=>undefined)});requestAnimationFrame(()=>existing.style.opacity='1');return existing}const firstLayer=overlay.firstElementChild as HTMLElement|null;if(!firstLayer)return null;const placeholder=firstLayer.querySelector<HTMLElement>('div[style*="place-items:center"]');const video=document.createElement('video');video.id='moniaVisioVideo';video.dataset.moniaVisualState=state;video.src=url;video.autoplay=true;video.muted=!transient||state!=='speaking';video.loop=true;video.playsInline=true;video.style.cssText='position:absolute;inset:0;width:100%;height:100%;object-fit:cover;background:#090807;transition:opacity .18s ease';if(placeholder)placeholder.replaceWith(video);else firstLayer.prepend(video);void video.play().catch(()=>{video.muted=true;void video.play().catch(()=>undefined)});return video}
function installNeutral(overlay:HTMLElement,state:LiveState){const video=overlay.querySelector<HTMLVideoElement>('#moniaVisioVideo')||overlay.querySelector<HTMLVideoElement>('.iphoneApprovedVisioVideo');if(video){video.pause();video.remove()}let neutral=overlay.querySelector<HTMLElement>('#moniaVisioNeutral');if(!neutral){neutral=document.createElement('div');neutral.id='moniaVisioNeutral';neutral.style.cssText='position:absolute;inset:0;display:grid;place-items:center;background:radial-gradient(circle at 50% 38%,rgba(116,91,72,.34),rgba(16,13,12,.92) 46%,#090807 100%);color:#fff;text-align:center;overflow:hidden';neutral.innerHTML='<div style="display:grid;place-items:center;gap:13px;transform:translateY(-2vh)"><div style="width:108px;height:108px;border-radius:50%;display:grid;place-items:center;background:rgba(255,255,255,.09);border:1px solid rgba(255,255,255,.14);box-shadow:0 22px 70px rgba(0,0,0,.32);font:500 42px/1 system-ui,sans-serif;letter-spacing:-.04em">D</div><strong style="font:600 18px/1.2 system-ui,sans-serif">Dominic</strong><small style="max-width:260px;color:rgba(255,255,255,.62);font:500 12px/1.45 system-ui,sans-serif">Caméra coupée · l’appel continue normalement</small></div>';const firstLayer=overlay.firstElementChild as HTMLElement|null;if(firstLayer)firstLayer.prepend(neutral);else overlay.prepend(neutral)}neutral.dataset.moniaVisualState=`${state}-camera-off`;return neutral}
function currentSpeechState():LiveState{if(forcedState)return forcedState;return'listening'}
function refresh(){const overlay=document.getElementById(OVERLAY_ID);if(!overlay)return;const state=currentSpeechState();const url=stateUrl(state);if(url){installVideo(overlay,url,state);setState(overlay,state);return}if(!hasApprovedLucasVisio()&&!readGameplayVisioTicket()){installNeutral(overlay,'listening');setState(overlay,'listening',true);return}installNeutral(overlay,state);setState(overlay,state,true)}

window.addEventListener('monia-visio-speech',event=>{const detail=(event as CustomEvent<SpeechDetail>).detail||{};if(detail.type==='thinking'){window.clearTimeout(reactionTimer);forcedState='thinking';refresh();return}if(detail.type==='start'){window.clearTimeout(reactionTimer);forcedState='speaking';refresh();return}if(detail.type==='boundary'){forcedState='speaking';refresh();return}if(detail.type==='end'||detail.type==='error'){forcedState='reaction';refresh();window.clearTimeout(reactionTimer);reactionTimer=window.setTimeout(()=>{forcedState=null;refresh()},1100)}});
window.setInterval(()=>{if(document.getElementById(OVERLAY_ID))refresh()},500);
window.addEventListener('storage',refresh);window.addEventListener('monia-visio-candidates',refresh);window.addEventListener('marion-lucas:gameplay-visio-ready',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});
console.info('[MonIA] Live visio states follow transient MonIA media first, approved media second; no generated candidate is auto-promoted');