import type { MonIAMaterializedMedia } from './experience-runtime';

const VISIO_MEDIA_KEY='monia-last-visio-media-v1';
const OVERLAY_ID='moniaVisioOverlay';
const MANIFEST_URL='./config/monia-visio-approved.json';
type LiveState='connecting'|'listening'|'speaking'|'reaction'|'media-error';
type SpeechDetail={type?:'start'|'boundary'|'end'|'error'};
type ApprovedManifest={fallback?:string;states?:{listening?:string|null;speaking?:string|null;reaction?:string|null}};

let forcedState:LiveState|null=null;
let reactionTimer=0;
let manifest:ApprovedManifest|null=null;
let manifestLoading=false;

function loadMedia():MonIAMaterializedMedia|null{try{const raw=sessionStorage.getItem(VISIO_MEDIA_KEY);return raw?JSON.parse(raw) as MonIAMaterializedMedia:null}catch{return null}}
async function loadManifest(){if(manifest||manifestLoading)return;manifestLoading=true;try{const r=await fetch(`${MANIFEST_URL}?v=1`,{cache:'no-store',credentials:'same-origin'});if(r.ok)manifest=await r.json() as ApprovedManifest}catch{}finally{manifestLoading=false;refresh()}}
function ensureStatus(overlay:HTMLElement){let badge=overlay.querySelector<HTMLElement>('[data-monia-live-state]');if(badge)return badge;badge=document.createElement('div');badge.dataset.moniaLiveState='connecting';badge.style.cssText='position:absolute;z-index:4;top:88px;left:24px;padding:7px 11px;border-radius:999px;background:rgba(0,0,0,.48);backdrop-filter:blur(9px);font:600 12px/1.2 system-ui,sans-serif;letter-spacing:.03em;color:#fff;border:1px solid rgba(255,255,255,.15)';overlay.appendChild(badge);return badge}
function setState(overlay:HTMLElement,state:LiveState,cameraOff=false){const badge=ensureStatus(overlay);badge.dataset.moniaLiveState=state;const label=state==='connecting'?'Connexion…':state==='speaking'?'Lucas parle':state==='reaction'?'Lucas réagit':state==='listening'?'Lucas écoute':'Vidéo indisponible';badge.textContent=`● ${label}${cameraOff&&state!=='connecting'?' · caméra coupée':''}`}
function approvedUrl(state:LiveState){const states=manifest?.states||{};if(state==='speaking'&&states.speaking)return states.speaking;if(state==='reaction'&&states.reaction)return states.reaction;if(state==='listening'&&states.listening)return states.listening;return manifest?.fallback||''}
function clearNeutral(overlay:HTMLElement){overlay.querySelector('#moniaVisioNeutral')?.remove()}
function installVideo(overlay:HTMLElement,url:string,state:LiveState){if(!url)return null;clearNeutral(overlay);const existing=overlay.querySelector<HTMLVideoElement>('#moniaVisioVideo');if(existing){const absolute=new URL(url,location.href).href;if(existing.src!==absolute){existing.style.opacity='.55';existing.src=url;existing.load();void existing.play().catch(()=>undefined);requestAnimationFrame(()=>existing.style.opacity='1')}existing.dataset.moniaVisualState=state;existing.playbackRate=1;return existing}const firstLayer=overlay.firstElementChild as HTMLElement|null;if(!firstLayer)return null;const placeholder=firstLayer.querySelector<HTMLElement>('div[style*="place-items:center"]');const video=document.createElement('video');video.id='moniaVisioVideo';video.dataset.moniaVisualState=state;video.src=url;video.autoplay=true;video.muted=true;video.loop=true;video.playsInline=true;video.style.cssText='position:absolute;inset:0;width:100%;height:100%;object-fit:cover;background:#090807;transition:opacity .18s ease';if(placeholder)placeholder.replaceWith(video);else firstLayer.prepend(video);void video.play().catch(()=>undefined);return video}
function installNeutral(overlay:HTMLElement,state:LiveState){const video=overlay.querySelector<HTMLVideoElement>('#moniaVisioVideo');if(video){video.pause();video.remove()}let neutral=overlay.querySelector<HTMLElement>('#moniaVisioNeutral');if(!neutral){neutral=document.createElement('div');neutral.id='moniaVisioNeutral';neutral.style.cssText='position:absolute;inset:0;display:grid;place-items:center;background:radial-gradient(circle at 50% 38%,rgba(116,91,72,.34),rgba(16,13,12,.92) 46%,#090807 100%);color:#fff;text-align:center;overflow:hidden';neutral.innerHTML='<div style="display:grid;place-items:center;gap:13px;transform:translateY(-2vh)"><div style="width:108px;height:108px;border-radius:50%;display:grid;place-items:center;background:rgba(255,255,255,.09);border:1px solid rgba(255,255,255,.14);box-shadow:0 22px 70px rgba(0,0,0,.32);font:500 42px/1 system-ui,sans-serif;letter-spacing:-.04em">L</div><strong style="font:600 18px/1.2 system-ui,sans-serif">Lucas</strong><small style="max-width:260px;color:rgba(255,255,255,.62);font:500 12px/1.45 system-ui,sans-serif">Caméra coupée · l’appel continue normalement</small></div>';const firstLayer=overlay.firstElementChild as HTMLElement|null;if(firstLayer)firstLayer.prepend(neutral);else overlay.prepend(neutral)}neutral.dataset.moniaVisualState=`${state}-camera-off`;return neutral}
function currentSpeechState():LiveState{if(forcedState)return forcedState;if(!('speechSynthesis'in window))return'listening';return window.speechSynthesis.speaking||window.speechSynthesis.pending?'speaking':'listening'}
function refresh(){const overlay=document.getElementById(OVERLAY_ID);if(!overlay)return;if(!manifest){void loadManifest();setState(overlay,'connecting');return}const state=currentSpeechState();const url=approvedUrl(state);if(url){installVideo(overlay,url,state);setState(overlay,state);return}installNeutral(overlay,state);const media=loadMedia();if(media?.state==='image-failed'||media?.state==='video-failed')setState(overlay,'media-error',true);else setState(overlay,state,true)}

window.addEventListener('monia-visio-speech',event=>{const detail=(event as CustomEvent<SpeechDetail>).detail||{};if(detail.type==='start'){window.clearTimeout(reactionTimer);forcedState='speaking';refresh();return}if(detail.type==='end'||detail.type==='error'){forcedState='reaction';refresh();window.clearTimeout(reactionTimer);reactionTimer=window.setTimeout(()=>{forcedState=null;refresh()},900)}});
let lastSpeaking=false;window.setInterval(()=>{const overlay=document.getElementById(OVERLAY_ID);if(!overlay)return;refresh();if('speechSynthesis'in window){const speaking=window.speechSynthesis.speaking||window.speechSynthesis.pending;if(speaking!==lastSpeaking){lastSpeaking=speaking;refresh()}}},500);
window.addEventListener('storage',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});void loadManifest();
console.info('[MonIA] Live visio uses approved video only, with intentional camera-off fallback');
