import './madrid-life-moments.css';
const SAVE_KEY='marion-lucas-save-v4';
const STATE_KEY='marion-lucas-madrid-moments-v1';

type Save={day?:number;time?:string;place?:string;screen?:string;stress?:number;energy?:number;relationship?:number;flags?:Record<string,unknown>;seed?:number};
type State={lastDay:number;shown:string[]};
type Choice={label:string;minutes:number;stress:number;energy:number;relationship:number;note:string};
type Moment={id:string;title:string;text:string;minHour:number;maxHour:number;choices:Choice[];visitOk?:boolean};

const MOMENTS:Moment[]=[
  {id:'friend-drops-by',title:'Quelqu’un passe à Madrid',text:'Un proche de Lucas est dans le quartier et propose de passer quelques minutes à la maison.',minHour:12,maxHour:21,visitOk:true,choices:[{label:'Le faire entrer',minutes:75,stress:-1,energy:-3,relationship:1,note:'La maison a pris un air plus vivant pendant un moment.'},{label:'Rester tranquilles',minutes:5,stress:-2,energy:1,relationship:1,note:'Ils ont préféré garder ce moment pour eux.'}]},
  {id:'late-return',title:'Retour tardif',text:'Ils rentrent à Madrid plus tard que prévu. La ville est encore réveillée, mais chez Lucas tout est enfin calme.',minHour:21,maxHour:23,visitOk:true,choices:[{label:'Se poser au salon',minutes:45,stress:-6,energy:2,relationship:2,note:'Le retour s’est terminé au calme, ensemble.'},{label:'Aller directement se coucher',minutes:20,stress:-3,energy:5,relationship:1,note:'Ils ont coupé court à la journée.'}]},
  {id:'before-going-out',title:'Encore un peu de temps',text:'Ils ont encore un moment devant eux avant de devoir repartir en ville.',minHour:16,maxHour:20,visitOk:true,choices:[{label:'Prendre un verre sur la terrasse',minutes:35,stress:-4,energy:0,relationship:2,note:'Ils ont profité de quelques minutes à deux avant de repartir.'},{label:'Rester au salon',minutes:30,stress:-3,energy:2,relationship:1,note:'Ils ont ralenti un peu avant la suite.'}]},
  {id:'office-door',title:'La lumière du bureau est encore allumée',text:'Lucas est passé par son bureau alors que la soirée avait déjà commencé.',minHour:18,maxHour:22,visitOk:true,choices:[{label:'Aller le rejoindre',minutes:30,stress:-1,energy:-1,relationship:2,note:'Le travail est resté quelques minutes au milieu de leur soirée.'},{label:'Le laisser finir',minutes:25,stress:-2,energy:1,relationship:0,note:'Marion lui a laissé un peu d’espace avant de se retrouver.'}]},
  {id:'dinner-at-home',title:'Finalement, ils restent ici',text:'Sortir n’a plus vraiment d’intérêt ce soir. La maison de Lucas est assez calme pour improviser quelque chose à deux.',minHour:19,maxHour:22,visitOk:true,choices:[{label:'Dîner ici',minutes:80,stress:-5,energy:1,relationship:3,note:'Le dîner improvisé a pris plus de temps que prévu.'},{label:'Commander quelque chose',minutes:45,stress:-4,energy:2,relationship:2,note:'Ils ont fait simple et sont restés chez Lucas.'}]},
];

function readSave():Save|null{try{const raw=localStorage.getItem(SAVE_KEY);return raw?JSON.parse(raw) as Save:null}catch{return null}}
function writeSave(s:Save){try{localStorage.setItem(SAVE_KEY,JSON.stringify(s));window.dispatchEvent(new Event('storage'));return true}catch{return false}}
function readState():State{try{const raw=localStorage.getItem(STATE_KEY);if(!raw)return{lastDay:-999,shown:[]};const p=JSON.parse(raw) as Partial<State>;return{lastDay:Number(p.lastDay??-999),shown:Array.isArray(p.shown)?p.shown:[]}}catch{return{lastDay:-999,shown:[]}}}
function writeState(s:State){try{localStorage.setItem(STATE_KEY,JSON.stringify(s));return true}catch{return false}}
function clamp(v:number){return Math.max(0,Math.min(100,Math.round(v)))}
function hour(s:Save){return Number(String(s.time||'12:00').slice(0,2))||12}
function addMinutes(s:Save,m:number){const p=String(s.time||'12:00').split(':').map(Number);let t=(p[0]||12)*60+(p[1]||0)+m;while(t>=1440){t-=1440;s.day=Math.max(1,Number(s.day||1)+1)}s.time=`${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`}
function deterministic(s:Save,salt:number){const seed=Number(s.seed||29),day=Number(s.day||1);return Math.abs(((seed*1664525+day*1013904223+salt*97)>>>0)%1000)/1000}
function mode(save:Save):'visit'|'home'|null{if(save.place!=='madrid')return null;const f=save.flags||{};if(Boolean(f.livingWithLucas||f.movedToMadrid||f.cohabitingMadrid))return'home';if(Boolean(f.visitingLucasMadrid||f.atLucasMadridHome||f.madridHomeVisit||f.stayingWithLucasMadrid))return'visit';return null}
function eligible(save:Save,state:State){const currentMode=mode(save);if(!currentMode||(save.screen&&save.screen!=='game'))return null;const day=Number(save.day||1);if(day-state.lastDay<3)return null;const h=hour(save),pool=MOMENTS.filter(m=>h>=m.minHour&&h<=m.maxHour&&(currentMode==='home'||m.visitOk)&&!state.shown.slice(-3).includes(m.id));if(!pool.length||deterministic(save,currentMode==='visit'?5:4)>(currentMode==='visit'?.22:.3))return null;return pool[Math.floor(deterministic(save,8)*pool.length)%pool.length]}
function esc(v:string){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c))}
function show(moment:Moment){if(document.getElementById('moniaMadridMoment'))return;const save=readSave(),currentMode=save?mode(save):null;const root=document.createElement('aside');root.id='moniaMadridMoment';root.className='madridLifeMoment';root.innerHTML=`<div class="madridLifeMomentCard"><small>${currentMode==='visit'?'CHEZ LUCAS · MADRID':'À MADRID'}</small><h3>${esc(moment.title)}</h3><p>${esc(moment.text)}</p><div>${moment.choices.map((c,i)=>`<button data-madrid-moment-choice="${i}">${esc(c.label)}</button>`).join('')}</div><button class="madridLifeMomentLater" data-madrid-moment-later>Pas maintenant</button></div>`;document.body.appendChild(root);root.querySelectorAll<HTMLButtonElement>('[data-madrid-moment-choice]').forEach(btn=>btn.onclick=()=>{const save=readSave();if(!save){root.remove();return}const c=moment.choices[Number(btn.dataset.madridMomentChoice||0)];addMinutes(save,c.minutes);save.stress=clamp(Number(save.stress??20)+c.stress);save.energy=clamp(Number(save.energy??70)+c.energy);save.relationship=clamp(Number(save.relationship??50)+c.relationship);const f=save.flags||(save.flags={});f.lastMadridLifeMoment=moment.id;f.lastMadridLifeMomentNote=c.note;const state=readState();state.lastDay=Number(save.day||1);state.shown=[...state.shown,moment.id].slice(-8);writeState(state);writeSave(save);root.remove();window.dispatchEvent(new CustomEvent('monia:madrid-life-moment',{detail:{id:moment.id,note:c.note}}))});root.querySelector<HTMLButtonElement>('[data-madrid-moment-later]')?.addEventListener('click',()=>{const save=readSave(),state=readState();if(save)state.lastDay=Math.max(state.lastDay,Number(save.day||1)-1);writeState(state);root.remove()})}
let timer=0;function schedule(){window.clearTimeout(timer);timer=window.setTimeout(()=>{const save=readSave();if(!save)return;const moment=eligible(save,readState());if(moment)show(moment)},900)}window.addEventListener('storage',schedule);window.addEventListener('monia:madrid-home-changed',schedule as EventListener);new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule();
