import './narrative-ui.css';
import { getLifeDirectorSnapshot } from './life-director';
import { executeDailyDirection, executeFreeIntent } from './daily-life-actions';

const SAVE_KEY='marion-lucas-save-v4';
type Save={screen?:string;overlay?:unknown;time?:string;day?:number;place?:string};

function readSave():Save|null{try{const raw=localStorage.getItem(SAVE_KEY);return raw?JSON.parse(raw) as Save:null}catch{return null}}
function esc(v:string){return v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]||c))}
function visible(){const s=readSave();return !!s&&s.screen==='game'&&!s.overlay&&!document.querySelector('.surprisePlayer,.cinematicOverlay,.phoneDevice[data-open="true"]')}
function mount(){let root=document.getElementById('moniaNarrativeUI');if(root)return root;root=document.createElement('section');root.id='moniaNarrativeUI';root.className='moniaNarrativeUI';document.body.appendChild(root);return root}
function render(){const root=mount();if(!visible()){root.classList.add('is-hidden');return}const snap=getLifeDirectorSnapshot();if(!snap){root.classList.add('is-hidden');return}root.classList.remove('is-hidden');const choices=snap.choices.slice(0,5).map((c,i)=>`<button class="moniaNarrativeChoice" data-life-choice="${esc(c.id)}"><span>${i+1}</span>${esc(c.label)}</button>`).join('');root.innerHTML=`<div class="moniaNarrativePanel"><div class="moniaNarrativeMeta">Jour ${snap.day} · ${esc(snap.time)}</div><p>${esc(snap.narrative)}</p><div class="moniaNarrativeChoices">${choices}</div><div class="moniaNarrativeFreedom"><button data-life-free="phone">Téléphone</button><button data-life-free="map">Carte</button><button data-life-free="wardrobe">Tenues</button><button data-life-free="journal">Journal</button><button class="moniaNarrativeWant" data-life-free="custom">J’ai envie de…</button></div><form class="moniaNarrativeCustom" hidden><input aria-label="J’ai envie de" maxlength="220" placeholder="Ex. appeler Lucas, aller à la plage, sortir avec Marine…"><button type="submit">Faire</button><button type="button" data-custom-close>×</button></form></div>`;}
function routeFree(kind:string){if(kind==='custom'){const form=document.querySelector<HTMLFormElement>('.moniaNarrativeCustom');if(form){form.hidden=false;form.querySelector('input')?.focus()}return}const intent=kind==='phone'?'open-phone':kind==='map'?'open-map':kind==='wardrobe'?'open-wardrobe':'open-journal';window.dispatchEvent(new CustomEvent('monia:daily-intent',{detail:{intent,source:'narrative-ui'}}));}
document.addEventListener('click',e=>{const t=e.target as HTMLElement;const choice=t.closest<HTMLElement>('[data-life-choice]');if(choice){executeDailyDirection(String(choice.dataset.lifeChoice||''));setTimeout(render,60);return}const free=t.closest<HTMLElement>('[data-life-free]');if(free){routeFree(String(free.dataset.lifeFree||''));return}if(t.closest('[data-custom-close]')){const f=document.querySelector<HTMLFormElement>('.moniaNarrativeCustom');if(f)f.hidden=true}});
document.addEventListener('submit',e=>{const form=(e.target as HTMLElement).closest<HTMLFormElement>('.moniaNarrativeCustom');if(!form)return;e.preventDefault();const input=form.querySelector<HTMLInputElement>('input');const text=input?.value.trim()||'';if(!text)return;const r=executeFreeIntent(text);if(r.ok){if(input)input.value='';form.hidden=true;setTimeout(render,60)}});
window.addEventListener('storage',e=>{if(e.key===SAVE_KEY)render()});window.addEventListener('monia:daily-intent',()=>setTimeout(render,80));new MutationObserver(()=>render()).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});setInterval(render,1500);setTimeout(render,350);
