import './ordinary-life-direction-bridge.css';
import { getDominicPresence } from './lucas-presence-engine';

const SAVE_KEY='marion-lucas-save-v4';
type Beat={id:string;kind:'quiet'|'practical'|'self'|'social'|'couple'|'outing';score:number;reason:string;place:string;time:string};
type Save={screen?:string;overlay?:unknown;place?:string};
let renderFrame=0,lastSignature='';
function read():Save|null{try{const raw=localStorage.getItem(SAVE_KEY);return raw?JSON.parse(raw) as Save:null}catch{return null}}
function esc(v:string){return v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]||c))}
function visible(){const s=read();return !!s&&s.screen==='game'&&!s.overlay&&!document.querySelector('.surprisePlayer,.cinematicOverlay,.phoneDevice[data-open="true"]')}
function norm(v:unknown){return String(v||'').trim().toLowerCase()}
function homeLike(place:string){return /home|appart|maison|family|famille|finca|estate|propri[eé]t[eé]|madrid|hotel|chambre/.test(norm(place))}
const labels:Record<string,string>={'tea-window':'Rester un peu près de la fenêtre','read-few-pages':'Lire quelques pages','music-floor':'Mettre un peu de musique','balcony-air':'Prendre l’air','late-sofa':'Se poser quelques minutes','tidy-drawer':'Ranger un petit coin','laundry-fold':'Plier ce qui traîne','kitchen-reset':'Remettre la cuisine en ordre','quick-groceries':'Faire une petite course','water-plants':'S’occuper des plantes','journal-note':'Noter quelque chose pour moi','personal-admin':'Régler deux petites choses','outfit-choice':'Choisir tranquillement ma tenue','photo-sort':'Regarder quelques photos','own-project':'Avancer un peu sur mon truc','friend-message':'Envoyer un petit message','short-coffee':'Prendre un café rapidement','family-checkin':'Prendre des nouvelles','voice-note-friend':'Envoyer un vocal','street-hello':'Profiter d’un petit moment dehors','shared-coffee':'Prendre un café avec Dominic','small-touch':'Rester près de Dominic un instant','quiet-kitchen':'Rester avec Dominic dans la cuisine','brief-checkin':'Prendre deux minutes avec Dominic','same-room-silence':'Rester simplement avec Dominic','short-walk':'Faire un petit tour','bakery-run':'Passer chercher quelque chose dehors','market-loop':'Faire un détour par le marché','errand-route':'Sortir faire une petite course','sunset-step-out':'Sortir quelques minutes'};
function suffix(id:string){return id.replace(/^ordinary-(quiet|practical|self|social|couple|outing)-/,'')}
function label(b:Beat){return labels[suffix(b.id)]||({quiet:'Prendre un moment calme',practical:'Faire un petit truc ici',self:'Prendre un moment pour moi',social:'Voir un peu quelqu’un',couple:'Rester un peu avec Dominic',outing:'Prendre un peu l’air'}[b.kind])}
function allowed(b:Beat,s:Save){if(b.kind==='couple'&&getDominicPresence()?.together!==true)return false;const id=suffix(b.id),place=String(s.place||b.place||'');if(['tea-window','read-few-pages','music-floor','balcony-air','late-sofa','tidy-drawer','laundry-fold','kitchen-reset','water-plants','shared-coffee','quiet-kitchen','same-room-silence'].includes(id)&&!homeLike(place))return false;return true}
function hotspotText(h:HTMLElement){return norm(`${h.getAttribute('aria-label')||''} ${h.textContent||''} ${h.dataset.action||''} ${h.dataset.hotspot||''} ${h.dataset.homeAction||''}`)}
function hotspotTerms(b:Beat){const id=suffix(b.id);if(/kitchen|coffee/.test(id))return['cuisine','kitchen'];if(/balcony|window|sunset|air/.test(id))return['balcon','terrasse','fenetre','fenêtre','window'];if(/sofa|read|music|same-room|small-touch/.test(id))return['canape','canapé','salon','sofa'];if(/plant/.test(id))return['plante','plant','balcon'];if(b.kind==='outing')return['sortie','porte','dehors','door'];return[]}
function findHotspot(stage:HTMLElement,b:Beat){const terms=hotspotTerms(b);if(!terms.length)return null;return [...stage.querySelectorAll<HTMLElement>('.gameHotspot')].find(h=>terms.some(t=>hotspotText(h).includes(t)))||null}
function clearDecor(){document.querySelectorAll<HTMLElement>('.gameHotspot[data-ordinary-life-beat]').forEach(h=>{delete h.dataset.ordinaryLifeBeat;h.classList.remove('has-ordinary-life');h.querySelector('.ordinaryHotspotHint')?.remove()})}
function bindDecor(beats:Beat[]){clearDecor();const stage=document.getElementById('homePhotoStage');if(!(stage instanceof HTMLElement))return new Set<string>();const used=new Set<string>();for(const b of beats){const h=findHotspot(stage,b);if(!h||h.dataset.ordinaryLifeBeat)continue;h.dataset.ordinaryLifeBeat=b.id;h.classList.add('has-ordinary-life');const hint=document.createElement('small');hint.className='ordinaryHotspotHint';hint.textContent=label(b);h.appendChild(hint);used.add(b.id)}return used}
function removeChoices(){document.querySelectorAll('[data-ordinary-life-choice]').forEach(el=>el.remove())}
function render(){if(!visible()){removeChoices();clearDecor();lastSignature='';return}const s=read(),host=document.querySelector<HTMLElement>('.moniaNarrativeChoices');if(!s)return;const beats=((window.__moniaOrdinaryLifeBeats?.()||[]) as Beat[]).filter(b=>allowed(b,s)).slice(0,3);const stage=document.getElementById('homePhotoStage');const signature=[s.place,getDominicPresence()?.together===true?'with-lucas':'without-lucas',stage?'home-stage':'no-stage',...beats.map(b=>b.id)].join('|');if(signature===lastSignature)return;lastSignature=signature;const decorUsed=bindDecor(beats);removeChoices();if(!host)return;const fallback=beats.filter(b=>!decorUsed.has(b.id)).slice(0,2);const existingCount=host.querySelectorAll('.moniaNarrativeChoice:not([data-ordinary-life-choice])').length;for(const b of fallback.slice(0,Math.max(0,5-existingCount))){const button=document.createElement('button');button.type='button';button.className='moniaNarrativeChoice moniaOrdinaryLifeChoice';button.dataset.ordinaryLifeChoice=b.id;button.innerHTML=`<span>·</span>${esc(label(b))}`;button.title=b.reason;host.appendChild(button)}}
function schedule(){if(renderFrame)return;renderFrame=requestAnimationFrame(()=>{renderFrame=0;render()})}
function consume(id:string){const result=window.__moniaConsumeOrdinaryLifeBeat?.(id);if(result?.ok){lastSignature='';schedule();return true}return false}
document.addEventListener('click',event=>{const target=event.target as HTMLElement;const decor=target.closest<HTMLElement>('.gameHotspot[data-ordinary-life-beat]');if(decor){const id=decor.dataset.ordinaryLifeBeat;if(id){event.preventDefault();event.stopPropagation();const originalAction=decor.dataset.homeAction||decor.dataset.action||decor.dataset.hotspot||decor.getAttribute('aria-label')||'';if(consume(id))window.dispatchEvent(new CustomEvent('monia:decor-micro-action',{detail:{beatId:id,originalAction,hotspot:hotspotText(decor)}}))}return}const button=target.closest<HTMLElement>('[data-ordinary-life-choice]');if(button){const id=button.dataset.ordinaryLifeChoice;if(id)consume(id)}} ,true);
window.addEventListener('monia:ordinary-life-opportunity',schedule);window.addEventListener('monia:save-changed',schedule);window.addEventListener('monia:daily-intent',schedule);new MutationObserver(m=>{if(m.some(x=>[...x.addedNodes,...x.removedNodes].some(n=>!(n instanceof Element)||(!n.closest?.('[data-ordinary-life-choice]')&&!n.closest?.('.ordinaryHotspotHint')))))schedule()}).observe(document.body,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule();
declare global{interface Window{__moniaOrdinaryLifeBeats?:()=>Beat[];__moniaConsumeOrdinaryLifeBeat?:(id:string)=>{ok:boolean;minutes:number}}}
