import './phoneMediaMessages.css';
import { getPhoneMediaMessages, sendPhonePhoto } from './phone-media-messages';

const SAVE_KEY='marion-lucas-save-v4';
type Message={from:string;text:string;day:number;read:boolean;thread?:string};
type Save={day?:number;time?:string;place?:string;metLucas?:boolean;messages?:Message[];flags?:Record<string,unknown>};
let applying=false;
function read():Save{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'{}') as Save}catch{return {}}}
function threadFor(s:Save,m:Message){if(m.thread)return m.thread;if(m.from!=='Toi')return m.from;return s.metLucas?'Lucas':'Marine'}
function safeAttr(v:string){return v.replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c))}
function showHint(text:string){let hint=document.querySelector<HTMLElement>('.phoneMediaHint');if(!hint){hint=document.createElement('div');hint.className='phoneMediaHint';document.querySelector('.phoneDevice')?.appendChild(hint)}hint.textContent=text;hint.classList.add('show');window.setTimeout(()=>hint?.classList.remove('show'),2600)}
function mediaFor(s:Save,m:Message){const thread=threadFor(s,m);return [...getPhoneMediaMessages()].reverse().find(x=>x.author===m.from&&x.thread===thread&&x.day===m.day&&x.text===m.text&&x.approved)||null}
function decorateBubbles(){if(applying)return;const thread=document.querySelector<HTMLElement>('.phoneDevice.isMessagesOpen .smsThread');if(!thread)return;const s=read(),name=document.querySelector<HTMLElement>('.phoneDevice.isMessagesOpen .nativeThreadHead strong')?.textContent?.trim()||'';const msgs=(s.messages||[]).filter(m=>threadFor(s,m)===name).slice(0,30).reverse();const bubbles=[...thread.querySelectorAll<HTMLElement>(':scope > article.msg')];applying=true;try{bubbles.forEach((bubble,i)=>{if(bubble.querySelector('.phoneMediaImage'))return;const m=msgs[i];if(!m)return;const media=mediaFor(s,m);if(!media)return;const img=document.createElement('img');img.className='phoneMediaImage';img.src=media.src;img.alt=media.kind==='selfie'?`Selfie de ${media.author==='Toi'?'Marion':media.author}`:'Photo envoyée dans la conversation';img.loading='lazy';img.dataset.phoneMediaId=media.id;const p=bubble.querySelector('p');if(p)bubble.insertBefore(img,p);else bubble.appendChild(img);bubble.classList.add('hasPhoneMedia')})}finally{applying=false}}
function mountComposer(){const phone=document.querySelector<HTMLElement>('.phoneDevice.isMessagesOpen');if(!phone)return;const content=phone.querySelector<HTMLElement>('#phoneContent');const name=content?.querySelector<HTMLElement>('.nativeThreadHead strong')?.textContent?.trim();if(!content||name!=='Lucas'){content?.querySelector('.phoneMediaComposer')?.remove();return}if(content.querySelector('.phoneMediaComposer'))return;const box=document.createElement('div');box.className='phoneMediaComposer';box.innerHTML='<button type="button" data-phone-media-menu aria-label="Envoyer une photo">📷</button><div class="phoneMediaChoices" hidden><button type="button" data-phone-media-kind="place">Photo du moment</button><button type="button" data-phone-media-kind="selfie">Selfie</button></div>';content.appendChild(box)}
function refresh(){window.setTimeout(()=>{mountComposer();decorateBubbles()},0)}
document.addEventListener('click',async e=>{const t=e.target as HTMLElement|null;if(!t)return;const menu=t.closest<HTMLElement>('[data-phone-media-menu]');if(menu){e.preventDefault();const choices=menu.parentElement?.querySelector<HTMLElement>('.phoneMediaChoices');if(choices)choices.hidden=!choices.hidden;return}const choice=t.closest<HTMLElement>('[data-phone-media-kind]');if(!choice)return;e.preventDefault();const kind=choice.dataset.phoneMediaKind==='selfie'?'selfie':'place';choice.closest<HTMLElement>('.phoneMediaChoices')!.hidden=true;const result=await sendPhonePhoto({author:'Toi',thread:'Lucas',kind,caption:kind==='selfie'?'Pour toi 🤍':'Regarde où je suis'});if(!result){showHint(kind==='selfie'?'Aucun selfie de Marion n’est encore validé pour l’envoi.':'Pas de photo canonique disponible pour ce lieu.');return}window.dispatchEvent(new CustomEvent('marion:phone-refresh'));showHint('Photo envoyée à Lucas.');refresh()},{capture:true});
window.addEventListener('marion:phone-refresh',refresh as EventListener);window.addEventListener('marion:statechange',refresh as EventListener);window.addEventListener('storage',refresh);new MutationObserver(refresh).observe(document.getElementById('app')||document.documentElement,{childList:true,subtree:true});refresh();
console.info('[Phone media] approved photos can render inside message bubbles');
