import { createTravelPlan } from './travel-continuity-engine';

const SAVE_KEY='marion-lucas-save-v4';
type CalendarItem={day?:number;time?:string;owner?:string;title?:string;note?:string;place?:string};
type Save={day?:number;time?:string;place?:string;official?:boolean;relationship?:number;trust?:number;energy?:number;calendar?:CalendarItem[];flags?:Record<string,unknown>};
export type ToreroTravelChoice='follow'|'stay-home'|'join-later'|'own-plans';
export type ToreroTravelSnapshot={active:boolean;runLength:number;cities:string[];choiceOpen:boolean;transport:{lucas:string;cuadrilla:string;longDistance:string};choices:Array<{id:ToreroTravelChoice;label:string;effect:string}>;};
function read():Save|null{try{const raw=localStorage.getItem(SAVE_KEY);return raw?JSON.parse(raw) as Save:null}catch{return null}}
function taurine(i:CalendarItem){return i.owner==='Lucas'&&/corrida|feria|toros|arène|arena|entraînement|deplacement|déplacement/i.test(`${i.title||''} ${i.note||''}`)}
function cityOf(i:CalendarItem){if(i.place)return String(i.place);const raw=`${i.title||''} ${i.note||''}`;const m=raw.match(/(?:à|a|·)\s*([A-ZÀ-Ý][A-Za-zÀ-ÿ\- ]{2,28})/);return m?.[1]?.trim()||'Déplacement professionnel'}
function upcomingTrips(s:Save){const day=Number(s.day||1);return(s.calendar||[]).filter(i=>taurine(i)&&Number(i.day||0)>=day&&Number(i.day||0)<=day+6).sort((a,b)=>Number(a.day)-Number(b.day))}
export function getToreroTravelSnapshot():ToreroTravelSnapshot|null{const s=read();if(!s)return null;const upcoming=upcomingTrips(s);const cities=[...new Set(upcoming.map(cityOf))];const active=upcoming.length>=2;return{active,runLength:upcoming.length,cities,choiceOpen:!!s.official&&upcoming.length>0,transport:{lucas:'Pour les déplacements de corrida: voiture avec chauffeur le plus souvent.',cuadrilla:'La cuadrilla suit séparément dans son camion avec le matériel.',longDistance:'Avion quand la distance rend la route peu logique.'},choices:[{id:'follow',label:'L’accompagner sur la tournée',effect:'Marion voyage avec Lucas sur ce déplacement taurino: voiture avec chauffeur ou avion selon la distance; la cuadrilla suit séparément.'},{id:'stay-home',label:'Rester à la maison',effect:'Marion garde sa propre semaine pendant que Lucas part travailler avec son équipe.'},{id:'join-later',label:'Le rejoindre plus tard',effect:'Lucas et la cuadrilla partent d’abord; Marion pourra le rejoindre ensuite par voiture ou avion.'},{id:'own-plans',label:'Garder mes propres projets',effect:'Les engagements personnels de Marion restent prioritaires pendant la tournée.'}]};}
export function chooseToreroTravel(choice:ToreroTravelChoice){const s=read();if(!s)return false;const f=s.flags||(s.flags={});f.toreroTravelChoice=choice;f.toreroTravelChoiceDay=Number(s.day||1);f.cuadrillaVehicle='camion';if(choice==='follow')f.travelWithLucas=true;if(choice==='stay-home'||choice==='own-plans'||choice==='join-later')f.travelWithLucas=false;localStorage.setItem(SAVE_KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('monia:save-changed',{detail:{key:SAVE_KEY}}));const next=upcomingTrips(s)[0];if(next){const destination=cityOf(next);const from=choice==='follow'?String(s.place||f.lucasCurrentPlace||'Madrid'):String(f.lucasCurrentPlace||'Madrid');const owner=choice==='follow'?'together':'Lucas';createTravelPlan({owner,from,to:destination,departDay:Number(next.day||s.day||1),departTime:String(next.time||s.time||'09:00'),source:'calendar',purpose:'taurine'});}return true}
declare global{interface Window{__moniaToreroTravel?:()=>ToreroTravelSnapshot|null;__moniaChooseToreroTravel?:(c:ToreroTravelChoice)=>boolean}}
window.__moniaToreroTravel=getToreroTravelSnapshot;window.__moniaChooseToreroTravel=chooseToreroTravel;
