import './coupleIntimacyDirector.css';

type SaveLike={day:number;time:string;place:string;screen:string;metLucas:boolean;official:boolean;relationship:number;trust:number;chemistry:number;stress:number;memories:string[];flags:Record<string,boolean|number|string>;updatedAt:number};
const SAVE_KEY='marion-lucas-save-v4';
let open=false,timer=0;
function read():SaveLike|null{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null') as SaveLike|null}catch{return null}}
function write(s:SaveLike){s.updatedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(s))}
function mins(t:string){const [h,m]=String(t||'09:00').split(':').map(Number);return(h||0)*60+(m||0)}
function addMemory(s:SaveLike,t:string){if(!Array.isArray(s.memories))s.memories=[];if(!s.memories.includes(t))s.memories.unshift(t);s.memories=s.memories.slice(0,120)}
function blocked(){return Boolean(document.querySelector('#overlay.open,.eventOverlay,.incomingCallOverlay,.moniaDramaScene,#moniaSceneOffer,.lucasSharedRoutineVeil,.lucasReunionMoodVeil,.coupleMicroTensionVeil,.coupleIntimacyVeil'))}
function sharedPrivatePlace(s:SaveLike){return ['finca','estate','madrid'].includes(s.place)}
function eligible(s:SaveLike){if(!s.metLucas||!s.official||s.screen!=='game'||document.hidden||blocked())return false;if(!sharedPrivatePlace(s))return false;if(Boolean(s.flags.lucasBusy)||Boolean(s.flags.lucasAway)||Boolean(s.flags.corridaLive))return false;if(Number(s.flags.coupleIntimacyDay||0)===s.day)return false;const t=mins(s.time);if(t<1110||t>1430)return false;const spark=Number(s.flags.publicPrivateChemistryDay||0)===s.day;if(Number(s.relationship||0)<48||Number(s.trust||0)<36||Number(s.chemistry||0)<(spark?30:32))return false;return true}
function sceneFor(s:SaveLike){const warm=Number(s.relationship||0)>=65,charged=Number(s.chemistry||0)>=48;const spark=Number(s.flags.publicPrivateChemistryDay||0)===s.day;const k=(s.day*29+Math.round(s.relationship||0)+Math.round(s.chemistry||0))%4;if(spark)return{tone:'charged',k:'ENFIN SEULS',t:'La journée avait gardé quelque chose en suspens.',b:'Dès que vous vous retrouvez seuls, le regard de Lucas change. Le geste discret de tout à l’heure n’a visiblement été oublié par aucun de vous deux.',a:'Rester près de lui',c:'Laisser encore durer un peu'};if(charged&&k===0)return{tone:'charged',k:'PLUS PRÈS',t:'Le silence change de nature.',b:'Lucas s’approche pour dire quelque chose, puis s’arrête. Son regard descend une seconde vers tes lèvres avant de revenir au tien.',a:'Rester là',c:'Lui sourire et reculer un peu'};if(charged&&k===1)return{tone:'kiss',k:'UN BAISER QUI DURE',t:'Il t’embrasse sans précipitation.',b:'Le reste de la pièce semble s’effacer quelques secondes. Quand il se recule, il reste encore tout près.',a:'Le laisser revenir',c:'Garder ce moment comme ça'};if(warm&&k===2)return{tone:'tender',k:'RIEN À PROUVER',t:'Vous vous retrouvez seuls enfin.',b:'Il vient s’asseoir près de toi, assez près pour que son genou touche le tien. La tendresse suffit déjà à remplir le silence.',a:'Te rapprocher',c:'Rester contre lui sans parler'};return{tone:'private',k:'PLUS TARD',t:'La maison est devenue calme.',b:'Vous êtes seuls, la journée est derrière vous, et la proximité devient plus intime sans avoir besoin d’être nommée.',a:'Rester avec lui',c:'Laisser la soirée ralentir'} }
function resolve(s:SaveLike,choice:'a'|'c',tone:string){s.flags.coupleIntimacyDay=s.day;s.flags.coupleIntimacyTone=tone;s.flags.coupleIntimacyChoice=choice;if(choice==='a'){s.relationship=Number(s.relationship||0)+1;s.trust=Number(s.trust||0)+1;if(tone==='charged'||tone==='kiss')s.chemistry=Number(s.chemistry||0)+1;addMemory(s,'Un moment intime avec Lucas a pris plus de place que prévu, sans avoir besoin de mots.')}else{addMemory(s,'Vous avez laissé un moment intime rester suspendu, sans le forcer à devenir autre chose.')}if((tone==='kiss'||(tone==='charged'&&Number(s.flags.publicPrivateChemistryDay||0)===s.day))&&choice==='a'&&Number(s.relationship||0)>=70&&Number(s.trust||0)>=55){s.flags.intimateFadePossible=true}write(s)}
function showFade(s:SaveLike){const game=document.querySelector<HTMLElement>('main.game');if(!game)return;const fade=document.createElement('div');fade.className='coupleIntimacyFade';fade.innerHTML='<div><span>PLUS TARD</span><strong>La porte se referme sur le reste du monde.</strong><small>La nuit continue hors champ.</small></div>';game.appendChild(fade);s.flags.coupleMadeLoveDay=s.day;s.flags.intimateFadePossible=false;s.flags.publicPrivateSpark=false;addMemory(s,'Vous avez partagé un moment d’intimité profonde, gardé hors champ.');write(s);setTimeout(()=>fade.classList.add('is-leaving'),4200);setTimeout(()=>fade.remove(),5600)}
function show(s:SaveLike){const game=document.querySelector<HTMLElement>('main.game');if(!game||open||!eligible(s))return;open=true;const e=sceneFor(s);const v=document.createElement('div');v.className=`coupleIntimacyVeil ${e.tone}`;v.innerHTML=`<section class="coupleIntimacyCard"><span>${e.k}</span><h2>${e.t}</h2><p>${e.b}</p><div><button id="intimacyA" class="primary">${e.a}</button><button id="intimacyC">${e.c}</button></div></section>`;game.appendChild(v);const close=()=>{v.classList.add('is-leaving');setTimeout(()=>{v.remove();open=false},260)};(v.querySelector('#intimacyA') as HTMLButtonElement).onclick=()=>{const f=read();if(f){resolve(f,'a',e.tone);const after=read();if(after&&Boolean(after.flags.intimateFadePossible))setTimeout(()=>showFade(after),700)}close()};(v.querySelector('#intimacyC') as HTMLButtonElement).onclick=()=>{const f=read();if(f)resolve(f,'c',e.tone);close()}}
function arm(){const s=read();if(!s||!eligible(s)){if(timer)clearTimeout(timer);timer=0;return}if(timer||open)return;timer=window.setTimeout(()=>{timer=0;const f=read();if(f)show(f)},15000+((s.day*83+Math.round(s.chemistry||0))%10000))}
window.addEventListener('storage',arm);document.addEventListener('visibilitychange',()=>{if(!document.hidden)arm()});new MutationObserver(arm).observe(document.documentElement,{childList:true,subtree:true});window.setInterval(arm,10000);arm();console.info('[Romance] sexual tension + non-graphic intimacy layer active');
