import './externalWorldPressureDirector.css';

type CalendarItem={owner:'Marion'|'Lucas'|'Nous';title:string;day:number;note:string};
type SaveLike={day:number;time:string;place:string;screen:string;metLucas:boolean;official:boolean;relationship:number;trust:number;chemistry:number;stress:number;calendar:CalendarItem[];memories:string[];flags:Record<string,boolean|number|string>;updatedAt:number};

const SAVE_KEY='marion-lucas-save-v4';
let active=false,timer=0;

function read():SaveLike|null{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null') as SaveLike|null}catch{return null}}
function write(s:SaveLike){s.updatedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(s))}
function mins(t:string){const [h,m]=String(t||'09:00').split(':').map(Number);return(h||0)*60+(m||0)}
function addMemory(s:SaveLike,t:string){if(!Array.isArray(s.memories))s.memories=[];if(!s.memories.includes(t))s.memories.unshift(t);s.memories=s.memories.slice(0,140)}
function blocked(){return Boolean(document.querySelector('#overlay.open,.eventOverlay,.incomingCallOverlay,.moniaDramaScene,#moniaSceneOffer,.coupleIntimacyVeil,.externalWorldPressure'))}
function relevant(item:CalendarItem){const text=`${item.title||''} ${item.note||''}`.toLowerCase();return /(corrida|arène|arena|entraîn|entrain|déplac|deplac|voyage|train|avion|presse|interview|famille|gala|réception|reception|costume|essayage|rendez-vous|rdv|tournage|photo|shoot)/.test(text)}
function typeFor(item:CalendarItem){const text=`${item.title||''} ${item.note||''}`.toLowerCase();if(/corrida|arène|arena/.test(text))return'corrida';if(/voyage|déplac|deplac|train|avion/.test(text))return'travel';if(/presse|interview|gala|réception|reception|photo|shoot/.test(text))return'public';if(/entraîn|entrain/.test(text))return'training';if(/famille/.test(text))return'family';return'work'}
function nextPressure(s:SaveLike){const items=Array.isArray(s.calendar)?s.calendar:[];return items.filter(i=>(i.owner==='Lucas'||i.owner==='Nous')&&(i.day===s.day||i.day===s.day+1)&&relevant(i)).sort((a,b)=>a.day-b.day)[0]||null}
function eligible(s:SaveLike){if(!s.metLucas||!s.official||s.screen!=='game'||document.hidden||blocked())return false;if(Number(s.flags.externalWorldPressureDay||0)===s.day)return false;if(mins(s.time)<510||mins(s.time)>1320)return false;return Boolean(nextPressure(s))||Boolean(s.flags.corridaLive)||Boolean(s.flags.lucasWorkedLong)}
function copyFor(s:SaveLike,item:CalendarItem|null){const type=item?typeFor(item):(Boolean(s.flags.corridaLive)?'corrida':'work');const tomorrow=Boolean(item&&item.day===s.day+1);if(type==='corrida')return tomorrow?['DEMAIN','Quelque chose change déjà dans son rythme.','Lucas parle moins de ce qui arrive. Il vérifie ses affaires, son téléphone, l’heure. Tu reconnais cette concentration qui prend de la place avant même le départ.']:['AUJOURD’HUI','Son monde professionnel prend toute la place autour de lui.','Il reste proche, mais son attention est déjà happée ailleurs. La tendresse n’a pas disparu : elle doit juste trouver moins de place.'];if(type==='travel')return['BAGAGES, HORAIRES, TÉLÉPHONE','La journée commence à se découper autrement.','Vous parlez en morceaux entre deux horaires. Rien de dramatique, simplement cette réalité : parfois son métier décide du rythme avant vous.'];if(type==='public')return['AUTOUR DE LUI','Il y a plus de monde, plus de messages, plus de regards.','Lucas passe facilement du privé au public. Toi, tu commences à reconnaître le moment précis où il remet cette version de lui-même en place.'];if(type==='training')return['AVANT LE TRAVAIL','Il est déjà dans sa journée avant même de partir.','Tu le vois se concentrer, répéter mentalement son rythme, vérifier ce qu’il lui faut. Ce n’est pas de la distance. C’est son métier qui entre dans la pièce.'];if(type==='family')return['DANS SON MONDE','La journée ne vous appartient pas complètement.','Il y a la famille, les habitudes, les obligations. Vous vous retrouvez entre les moments, parfois juste avec un regard qui dit « je suis là ».'];return['UNE JOURNÉE PLUS SERRÉE','Son agenda déborde un peu sur votre espace.','Il répond à un message, repart sur autre chose, revient vers toi. Votre couple apprend aussi à vivre dans ces interstices.']}
function show(s:SaveLike){if(active||!eligible(s))return;const game=document.querySelector<HTMLElement>('main.game');if(!game)return;active=true;const item=nextPressure(s);const [k,t,b]=copyFor(s,item);const card=document.createElement('aside');card.id='externalWorldPressure';card.className='externalWorldPressure';card.innerHTML=`<span>${k}</span><strong>${t}</strong><small>${b}</small>`;game.appendChild(card);const pressureType=item?typeFor(item):(Boolean(s.flags.corridaLive)?'corrida':'work');s.flags.externalWorldPressureDay=s.day;s.flags.externalWorldPressureType=pressureType;s.flags.externalWorldPressureActive=true;s.flags.externalWorldPressureAt=mins(s.time);if(item)s.flags.externalWorldPressureCalendarDay=item.day;addMemory(s,'Le monde extérieur de Lucas a pris de la place dans votre journée sans effacer votre intimité.');write(s);setTimeout(()=>card.classList.add('is-leaving'),6200);setTimeout(()=>{card.remove();active=false},7900)}
function arm(){const s=read();if(!s||!eligible(s)){if(timer)clearTimeout(timer);timer=0;return}if(active||timer)return;timer=window.setTimeout(()=>{timer=0;const f=read();if(f)show(f)},10000+((s.day*97+mins(s.time))%7000))}

window.addEventListener('storage',arm);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)arm()});
window.setInterval(arm,12000);
arm();
console.info('[Romance] external world pressure now feeds couple rhythm without inventing canon events');
