import './firstDayComfort.css';

type Msg={from:string;text:string;day:number;read:boolean};
type SaveLike={day:number;time:string;place:string;screen:string;metLucas:boolean;outfit?:string;phoneUnread?:number;messages?:Msg[];flags:Record<string,boolean|number|string>;updatedAt:number};
const SAVE_KEY='marion-lucas-save-v4';
let toastTimer=0,guideTimer=0;

function read():SaveLike|null{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null') as SaveLike|null}catch{return null}}
function write(s:SaveLike){s.updatedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(s))}
function mins(t:string){const [h,m]=String(t||'09:00').split(':').map(Number);return (h||0)*60+(m||0)}
function nowStamp(s:SaveLike){return s.day*1440+mins(s.time)}
function isFirstHome(s:SaveLike|null){return Boolean(s&&s.day===1&&s.place==='home'&&!s.metLucas&&s.screen==='game')}
function noteFlag(key:string,value:boolean|string|number=true){window.setTimeout(()=>{const s=read();if(!s)return;s.flags[key]=value;write(s)},80)}
function latestIncoming(s:SaveLike){return (s.messages||[]).find(m=>m.from&&m.from!=='Toi')||null}
function hasUnread(s:SaveLike){const incoming=latestIncoming(s);return Number(s.phoneUnread||0)>0||Boolean(incoming&&!incoming.read)}
function invitationWaiting(s:SaveLike){const thread=String(s.flags.dayOneThread||'');if(thread.startsWith('marine_')&&thread!=='marine_later')return true;const m=latestIncoming(s);return Boolean(m&&m.read&&/(ar[eè]nes|viens|rejoins|caf[eé]|on se voit|je t.attends)/i.test(m.text||''))}
function invitationDeferred(s:SaveLike){const until=Number(s.flags.firstDayInvitationDeferredUntil||0);return until>nowStamp(s)||String(s.flags.dayOneSuggestedAction||'')==='freeMorning'}

function showToast(title:string,body:string,duration=2300){document.querySelector('.firstDayComfortToast')?.remove();const toast=document.createElement('aside');toast.className='firstDayComfortToast';toast.innerHTML=`<strong>${title}</strong><small>${body}</small>`;document.body.appendChild(toast);if(toastTimer)window.clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>{toast.classList.add('is-leaving');window.setTimeout(()=>toast.remove(),260)},duration)}
function clickOne(selectors:string){for(const sel of selectors.split(',')){const el=document.querySelector<HTMLElement>(sel.trim());if(el){el.click();return true}}return false}
function guideCopy(s:SaveLike){
  const deferred=invitationDeferred(s),suggested=String(s.flags.dayOneSuggestedAction||'');
  if(hasUnread(s))return{eyebrow:'TON TÉLÉPHONE VIBRE',title:'Tu as reçu un message.',body:'Tu peux le lire maintenant. Ce qui arrive ensuite dépendra de ce que tu décides.',primary:'Lire le message',primaryAction:'phone',secondary:'Me préparer d’abord',secondaryAction:'wardrobe'};
  if(suggested==='goMarine')return{eyebrow:'C’EST DÉCIDÉ',title:'Tu as répondu que tu arrivais.',body:'Le jeu garde ta décision en tête. Tu peux maintenant simplement poursuivre dans cette direction.',primary:'Sortir',primaryAction:'map',secondary:'Téléphone',secondaryAction:'phone'};
  if(suggested==='prepareThenMarine'&&!s.flags.firstDayChoseOutfit)return{eyebrow:'AVANT DE SORTIR',title:'Tu as dit que tu te préparais.',body:'Choisis une tenue, puis la matinée reprendra naturellement à partir de ta réponse.',primary:'Choisir une tenue',primaryAction:'wardrobe',secondary:'Sortir maintenant',secondaryAction:'map'};
  if(suggested==='prepareThenMarine'&&s.flags.firstDayChoseOutfit)return{eyebrow:'TU ES PRÊTE',title:'Tu peux maintenant sortir.',body:'Ta réponse est toujours prise en compte. Le jeu sait exactement où tu en es.',primary:'Sortir',primaryAction:'map',secondary:'Téléphone',secondaryAction:'phone'};
  if(suggested==='freeMorning')return{eyebrow:'TU PRENDS TON TEMPS',title:'Tu n’as rien promis pour tout de suite.',body:'Tu peux faire autre chose. Le monde continuera d’avancer et pourra revenir vers toi plus tard.',primary:'Me préparer',primaryAction:'wardrobe',secondary:'Voir mon téléphone',secondaryAction:'phone'};
  if(invitationWaiting(s)&&!deferred){if(!s.flags.firstDayChoseOutfit)return{eyebrow:'UN PLAN SE DESSINE',title:'Quelqu’un t’attend en ville.',body:'Tu peux suivre cette piste tout de suite, ou te préparer avant de sortir.',primary:'Voir la suite',primaryAction:'map',secondary:'Me préparer',secondaryAction:'wardrobe'};return{eyebrow:'À TOI DE DÉCIDER',title:'Tu es prête à sortir.',body:'Tu as une direction possible. Tu peux la suivre, ou rester encore un peu chez toi.',primary:'Continuer',primaryAction:'map',secondary:'Rester un peu',secondaryAction:'defer'};}
  if(invitationWaiting(s)&&deferred)return{eyebrow:'UN PEU DE TEMPS POUR TOI',title:'Tu n’es pas obligée de partir tout de suite.',body:'Profite encore de l’appartement. Le jeu te relancera naturellement si quelque chose change.',primary:'Choisir une tenue',primaryAction:'wardrobe',secondary:'Voir mon téléphone',secondaryAction:'phone'};
  if(!s.flags.firstDayChoseOutfit)return{eyebrow:'POUR COMMENCER',title:'Prépare-toi pour la journée.',body:'Tu gardes la main, mais le monde autour de toi va commencer à bouger.',primary:'Choisir une tenue',primaryAction:'wardrobe',secondary:'Téléphone',secondaryAction:'phone'};
  return{eyebrow:'TA MATINÉE EST LANCÉE',title:'Tu as une piste, pas une obligation.',body:'Suis ce qui se présente, ou utilise librement ton téléphone, ta carte et ton agenda.',primary:'Voir où aller',primaryAction:'map',secondary:'Téléphone',secondaryAction:'phone'};
}
function renderTutorial(s:SaveLike,host:HTMLElement){let tip=document.querySelector<HTMLElement>('.firstDayTutorial');if(s.flags.firstDayTutorialSeen){tip?.remove();return}if(!tip){tip=document.createElement('aside');tip.className='firstDayTutorial';tip.innerHTML='<button class="firstDayTutorialClose" data-tutorial-done aria-label="Fermer">×</button><span>PREMIERS PAS</span><strong>Tu peux suivre le jeu sans perdre ta liberté.</strong><div><small>• Les propositions te donnent une direction.</small><small>• Ton téléphone sert à parler réellement aux personnages.</small><small>• Tes réponses et tes choix peuvent changer la suite.</small></div><button class="firstDayTutorialOk" data-tutorial-done>Compris</button>';host.appendChild(tip)}}
function renderGuide(){const s=read(),host=document.querySelector<HTMLElement>('.immersivePlayable');const old=document.querySelector<HTMLElement>('.firstDayGuide');if(!isFirstHome(s)||!host){old?.remove();document.querySelector('.firstDayTutorial')?.remove();return}renderTutorial(s!,host);const c=guideCopy(s!);let card=old;if(!card){card=document.createElement('aside');card.className='firstDayGuide';host.appendChild(card)}card.innerHTML=`<div class="firstDayGuideCopy"><span>${c.eyebrow}</span><strong>${c.title}</strong><small>${c.body}</small></div><div class="firstDayGuideActions"><button class="firstDayPrimary" data-guide-action="${c.primaryAction}">${c.primary}</button><button data-guide-action="${c.secondaryAction}">${c.secondary}</button></div>`}
function scheduleGuide(){if(guideTimer)window.clearTimeout(guideTimer);guideTimer=window.setTimeout(renderGuide,90)}

function decorateWardrobe(){const s=read();if(!isFirstHome(s))return;const panel=document.querySelector<HTMLElement>('.wardrobeStudio');if(!panel||panel.querySelector('.firstWardrobeComfort'))return;const note=document.createElement('div');note.className='firstWardrobeComfort';note.innerHTML='<span>PREMIER MATIN</span><strong>Choisis ce qui te ressemble.</strong><small>La tenue peut accompagner le moment, mais aucune option n’est une “bonne réponse”.</small>';panel.prepend(note);noteFlag('firstWardrobeComfortSeen')}
function decorateWorld(){const s=read();if(!isFirstHome(s))return;const panel=document.querySelector<HTMLElement>('.worldGalleryPanel');if(!panel)return;const nimes=panel.querySelector<HTMLButtonElement>('[data-place="nimes"]');if(!nimes)return;nimes.classList.add('firstDaySuggestedPlace');if(!panel.querySelector('.firstMapComfort')){const title=panel.querySelector('.screenTitle');const note=document.createElement('div');note.className='firstMapComfort';note.innerHTML='<span>DIRECTION DU MOMENT</span><strong>Une piste t’emmène vers le centre.</strong><small>Tu peux la suivre sans savoir ce que la journée te réserve ensuite.</small>';title?.appendChild(note)}noteFlag('firstMapComfortSeen')}
function exitVeil(){document.querySelector('.firstDayExitVeil')?.remove();const veil=document.createElement('div');veil.className='firstDayExitVeil';veil.innerHTML='<div><span>NÎMES</span><strong>Tu attrapes tes affaires.</strong><small>Dehors, la journée continue sans t’attendre.</small></div>';document.body.appendChild(veil);window.setTimeout(()=>veil.classList.add('is-visible'),20);window.setTimeout(()=>veil.classList.add('is-leaving'),900);window.setTimeout(()=>veil.remove(),1450)}

function handleClick(e:MouseEvent){const target=e.target as HTMLElement|null;if(!target)return;if(target.closest('[data-tutorial-done]')){const s=read();if(s){s.flags.firstDayTutorialSeen=true;write(s)}document.querySelector('.firstDayTutorial')?.remove();scheduleGuide();return}const guide=target.closest<HTMLElement>('[data-guide-action]');if(guide){const a=guide.dataset.guideAction;if(a==='phone')clickOne('#premiumPhone,#phone,#phoneExact');if(a==='wardrobe')clickOne('#premiumWardrobe,#goWardrobe');if(a==='map')clickOne('#premiumMap,#worldQuick,#worldExact,#goWorld');if(a==='defer'){const s=read();if(s){s.flags.firstDayInvitationDeferredUntil=nowStamp(s)+30;s.flags.dayOneSuggestedAction='freeMorning';write(s)}showToast('Tu prends ton temps.','Le jeu garde ce qui s’est passé en mémoire. Tu peux faire autre chose avant.')}window.setTimeout(scheduleGuide,160);return}const s=read();if(target.closest('#premiumWardrobe,#goWardrobe'))window.setTimeout(decorateWardrobe,80);if(target.closest('#premiumMap,#worldQuick,#worldExact,#goWorld'))window.setTimeout(decorateWorld,80);if(isFirstHome(s)&&target.closest('.wardrobeStudio [data-outfit]')){const fresh=read();if(fresh){fresh.flags.firstDayChoseOutfit=true;if(String(fresh.flags.dayOneSuggestedAction||'')==='freeMorning')fresh.flags.dayOneSuggestedAction='';write(fresh)}window.setTimeout(()=>showToast('C’est bon.','Le jeu a enregistré ton choix. Tu peux maintenant poursuivre naturellement.'),120);window.setTimeout(scheduleGuide,180)}const place=target.closest<HTMLElement>('[data-place]')?.dataset.place;if(isFirstHome(s)&&place==='nimes'){const fresh=read();if(fresh){fresh.flags.firstDayLeftHomeComfortably=true;fresh.flags.dayOneSuggestedAction='';write(fresh)}exitVeil()}window.setTimeout(scheduleGuide,140)}

document.addEventListener('click',handleClick,{passive:true,capture:true});new MutationObserver(scheduleGuide).observe(document.getElementById('app')||document.documentElement,{childList:true,subtree:true});window.addEventListener('storage',scheduleGuide);window.setInterval(scheduleGuide,12000);scheduleGuide();console.info('[Day 1] phone choices now drive the guided story flow');
