import './firstDayComfort.css';

type Msg={from:string;text:string;day:number;read:boolean};
type SaveLike={day:number;time:string;place:string;screen:string;metLucas:boolean;outfit?:string;phoneUnread?:number;messages?:Msg[];flags:Record<string,boolean|number|string>;updatedAt:number};
const SAVE_KEY='marion-lucas-save-v4';
let toastTimer=0,guideTimer=0;

function read():SaveLike|null{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null') as SaveLike|null}catch{return null}}
function write(s:SaveLike){s.updatedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(s))}
function isFirstHome(s:SaveLike|null){return Boolean(s&&s.day===1&&s.place==='home'&&!s.metLucas&&s.screen==='game')}
function noteFlag(key:string,value:boolean|string=true){window.setTimeout(()=>{const s=read();if(!s)return;s.flags[key]=value;write(s)},80)}
function latestIncoming(s:SaveLike){return [...(s.messages||[])].reverse().find(m=>m.from&&m.from!=='Toi')||null}

function showToast(title:string,body:string,duration=2300){document.querySelector('.firstDayComfortToast')?.remove();const toast=document.createElement('aside');toast.className='firstDayComfortToast';toast.innerHTML=`<strong>${title}</strong><small>${body}</small>`;document.body.appendChild(toast);if(toastTimer)window.clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>{toast.classList.add('is-leaving');window.setTimeout(()=>toast.remove(),260)},duration)}
function clickOne(selectors:string){for(const sel of selectors.split(',')){const el=document.querySelector<HTMLElement>(sel.trim());if(el){el.click();return true}}return false}
function guideCopy(s:SaveLike){const incoming=latestIncoming(s),hasUnread=Number(s.phoneUnread||0)>0||Boolean(incoming&&!incoming.read);if(hasUnread)return{eyebrow:'TON MATIN COMMENCE',title:'Tu as reçu un message.',body:'Tu peux le lire maintenant, ou continuer à te préparer avant de décider.',primary:'Lire le message',primaryAction:'phone',secondary:'Me préparer',secondaryAction:'wardrobe'};if(!s.flags.firstDayChoseOutfit)return{eyebrow:'PREMIER MATIN',title:'Commence tranquillement.',body:'Le jeu te propose une direction, mais tu restes libre de faire autrement.',primary:'Me préparer',primaryAction:'wardrobe',secondary:'Voir où sortir',secondaryAction:'map'};return{eyebrow:'ET MAINTENANT ?',title:'La journée peut commencer.',body:'Tu peux suivre la piste proposée ou faire autre chose. Les imprévus viendront aussi d’eux-mêmes.',primary:'Voir où sortir',primaryAction:'map',secondary:'Téléphone',secondaryAction:'phone'}}
function renderGuide(){const s=read(),host=document.querySelector<HTMLElement>('.immersivePlayable');const old=document.querySelector<HTMLElement>('.firstDayGuide');if(!isFirstHome(s)||!host){old?.remove();return}const c=guideCopy(s!);let card=old;if(!card){card=document.createElement('aside');card.className='firstDayGuide';host.appendChild(card)}card.innerHTML=`<div class="firstDayGuideCopy"><span>${c.eyebrow}</span><strong>${c.title}</strong><small>${c.body}</small></div><div class="firstDayGuideActions"><button class="firstDayPrimary" data-guide-action="${c.primaryAction}">${c.primary}</button><button data-guide-action="${c.secondaryAction}">${c.secondary}</button></div>`}
function scheduleGuide(){if(guideTimer)window.clearTimeout(guideTimer);guideTimer=window.setTimeout(renderGuide,90)}

function decorateWardrobe(){const s=read();if(!isFirstHome(s))return;const panel=document.querySelector<HTMLElement>('.wardrobeStudio');if(!panel||panel.querySelector('.firstWardrobeComfort'))return;const note=document.createElement('div');note.className='firstWardrobeComfort';note.innerHTML='<span>PREMIER MATIN</span><strong>Choisis juste ce qui te ressemble.</strong><small>Aucune tenue n’est “meilleure”.</small>';panel.prepend(note);noteFlag('firstWardrobeComfortSeen')}
function decorateWorld(){const s=read();if(!isFirstHome(s))return;const panel=document.querySelector<HTMLElement>('.worldGalleryPanel');if(!panel)return;const nimes=panel.querySelector<HTMLButtonElement>('[data-place="nimes"]');if(!nimes)return;nimes.classList.add('firstDaySuggestedPlace');if(!panel.querySelector('.firstMapComfort')){const title=panel.querySelector('.screenTitle');const note=document.createElement('div');note.className='firstMapComfort';note.innerHTML='<span>POUR SORTIR</span><strong>Nîmes est juste là.</strong><small>Tu peux suivre cette piste maintenant, ou revenir à ta journée.</small>';title?.appendChild(note)}noteFlag('firstMapComfortSeen')}
function exitVeil(){document.querySelector('.firstDayExitVeil')?.remove();const veil=document.createElement('div');veil.className='firstDayExitVeil';veil.innerHTML='<div><span>NÎMES</span><strong>Tu attrapes tes affaires.</strong><small>La porte se referme derrière toi.</small></div>';document.body.appendChild(veil);window.setTimeout(()=>veil.classList.add('is-visible'),20);window.setTimeout(()=>veil.classList.add('is-leaving'),900);window.setTimeout(()=>veil.remove(),1450)}

function handleClick(e:MouseEvent){const target=e.target as HTMLElement|null;if(!target)return;const guide=target.closest<HTMLElement>('[data-guide-action]');if(guide){const a=guide.dataset.guideAction;if(a==='phone')clickOne('#premiumPhone,#phone,#phoneExact');if(a==='wardrobe')clickOne('#premiumWardrobe,#goWardrobe');if(a==='map')clickOne('#premiumMap,#worldQuick,#worldExact,#goWorld');window.setTimeout(scheduleGuide,120);return}const s=read();if(target.closest('#premiumWardrobe,#goWardrobe'))window.setTimeout(decorateWardrobe,80);if(target.closest('#premiumMap,#worldQuick,#worldExact,#goWorld'))window.setTimeout(decorateWorld,80);if(isFirstHome(s)&&target.closest('.wardrobeStudio [data-outfit]')){noteFlag('firstDayChoseOutfit');window.setTimeout(()=>showToast('Ça te va.','Tu peux maintenant poursuivre ta matinée.'),120);window.setTimeout(scheduleGuide,180)}const place=target.closest<HTMLElement>('[data-place]')?.dataset.place;if(isFirstHome(s)&&place==='nimes'){exitVeil();noteFlag('firstDayLeftHomeComfortably')}window.setTimeout(scheduleGuide,140)}

document.addEventListener('click',handleClick,{passive:true,capture:true});new MutationObserver(scheduleGuide).observe(document.getElementById('app')||document.documentElement,{childList:true,subtree:true});window.addEventListener('storage',scheduleGuide);scheduleGuide();console.info('[Day 1] guided-but-free first morning active');
