import './intimacyAfterglowDirector.css';

type SaveLike={day:number;time:string;place:string;screen:string;metLucas:boolean;official:boolean;relationship:number;trust:number;chemistry:number;stress:number;memories:string[];flags:Record<string,boolean|number|string>;updatedAt:number};
const SAVE_KEY='marion-lucas-save-v4';
let timer=0,active=false;
function read():SaveLike|null{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null') as SaveLike|null}catch{return null}}
function write(s:SaveLike){s.updatedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(s))}
function mins(t:string){const [h,m]=String(t||'09:00').split(':').map(Number);return(h||0)*60+(m||0)}
function addMemory(s:SaveLike,t:string){if(!Array.isArray(s.memories))s.memories=[];if(!s.memories.includes(t))s.memories.unshift(t);s.memories=s.memories.slice(0,130)}
function blocked(){return Boolean(document.querySelector('#overlay.open,.eventOverlay,.incomingCallOverlay,.moniaDramaScene,#moniaSceneOffer,.coupleIntimacyVeil,.coupleIntimacyFade,.intimacyAfterglow'))}
function sharedPlace(s:SaveLike){return['finca','estate','madrid'].includes(s.place)}
function eligible(s:SaveLike){if(!s.metLucas||!s.official||s.screen!=='game'||document.hidden||blocked()||!sharedPlace(s))return false;const made=Number(s.flags.coupleMadeLoveDay||0);if(!made)return false;if(s.day-made>1)return false;if(Number(s.flags.intimacyAfterglowDay||0)===s.day)return false;const t=mins(s.time);return t>=390&&t<=1260}
function sceneFor(s:SaveLike){const made=Number(s.flags.coupleMadeLoveDay||0);const sameDay=made===s.day;const close=Number(s.relationship||0)>=72;const k=(s.day*41+Math.round(s.chemistry||0)+Math.round(s.trust||0))%4;if(sameDay&&mins(s.time)>=390&&mins(s.time)<600)return{tone:'morning',k:'LE MATIN D’APRÈS',t:'Le silence n’a plus tout à fait la même texture.',b:'Lucas est encore tout près. Pas de grande phrase, juste cette douceur un peu différente dans sa façon de te regarder.'};if(k===0)return{tone:'glance',k:'PLUS TARD',t:'Un regard suffit.',b:'Vous vous croisez dans la maison. Son regard s’attarde une seconde de trop, comme s’il se souvenait exactement de la nuit sans avoir besoin de la nommer.'};if(k===1&&close)return{tone:'touch',k:'EN PASSANT',t:'Sa main trouve naturellement la tienne.',b:'Le geste est simple, presque banal. Mais cette fois, il porte encore quelque chose de la nuit précédente.'};if(k===2)return{tone:'charged',k:'RIEN QU’UN DÉTAIL',t:'La proximité revient sans prévenir.',b:'Il passe derrière toi, assez près pour réveiller instantanément ce souvenir physique entre vous. Puis il continue comme si de rien n’était.'};return{tone:'soft',k:'ENTRE VOUS',t:'Quelque chose a changé sans devenir spectaculaire.',b:'Vous reprenez votre journée normalement. C’est justement cette normalité-là qui rend le moment précédent encore plus intime.'}}
function show(s:SaveLike){if(active||!eligible(s))return;const game=document.querySelector<HTMLElement>('main.game');if(!game)return;active=true;const e=sceneFor(s);const card=document.createElement('aside');card.id='intimacyAfterglow';card.className=`intimacyAfterglow ${e.tone}`;card.innerHTML=`<span>${e.k}</span><strong>${e.t}</strong><small>${e.b}</small>`;game.appendChild(card);s.flags.intimacyAfterglowDay=s.day;s.flags.intimacyAfterglowTone=e.tone;s.relationship=Number(s.relationship||0)+1;if(e.tone==='charged'||e.tone==='glance')s.chemistry=Number(s.chemistry||0)+1;addMemory(s,'L’intimité partagée avec Lucas a continué d’exister dans les petits gestes du lendemain.');write(s);setTimeout(()=>card.classList.add('is-leaving'),6200);setTimeout(()=>{card.remove();active=false},7900)}
function arm(){const s=read();if(!s||!eligible(s)){if(timer)clearTimeout(timer);timer=0;return}if(timer||active)return;timer=window.setTimeout(()=>{timer=0;const f=read();if(f)show(f)},9000+((s.day*67+Math.round(s.chemistry||0))%7000))}
window.addEventListener('storage',arm);document.addEventListener('visibilitychange',()=>{if(!document.hidden)arm()});new MutationObserver(arm).observe(document.documentElement,{childList:true,subtree:true});window.setInterval(arm,8000);arm();console.info('[Romance] intimacy afterglow + next-day desire memory active');
