import './marionPlaceInLucasWorldDirector.css';

type SaveLike={day:number;time:string;place:string;screen:string;metLucas:boolean;official:boolean;relationship:number;trust:number;stress:number;memories:string[];flags:Record<string,boolean|number|string>;updatedAt:number};
const SAVE_KEY='marion-lucas-save-v4';
let active=false,timer=0;
function read():SaveLike|null{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null') as SaveLike|null}catch{return null}}
function write(s:SaveLike){s.updatedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(s))}
function mins(t:string){const [h,m]=String(t||'09:00').split(':').map(Number);return(h||0)*60+(m||0)}
function addMemory(s:SaveLike,t:string){if(!Array.isArray(s.memories))s.memories=[];if(!s.memories.includes(t))s.memories.unshift(t);s.memories=s.memories.slice(0,180)}
function blocked(){return Boolean(document.querySelector('#overlay.open,.eventOverlay,.incomingCallOverlay,.moniaDramaScene,#moniaSceneOffer,.postEventReunion,.travelWithLucas,.travelSocialOrbit,.marionPlaceLucasWorld'))}
function lucasWorldPlace(s:SaveLike){return['madrid','family','arenes','finca','estate','station'].includes(s.place)}
function markExposure(s:SaveLike){if(!lucasWorldPlace(s)||!s.official)return false;const key=`lucasWorldExposure_${s.day}`;if(Boolean(s.flags[key]))return false;s.flags[key]=true;s.flags.lucasWorldExposureDays=Number(s.flags.lucasWorldExposureDays||0)+1;write(s);return true}
function stageFor(s:SaveLike){const days=Number(s.flags.lucasWorldExposureDays||0);if(days>=8&&Number(s.trust||0)>=58)return 4;if(days>=6&&Number(s.trust||0)>=50)return 3;if(days>=4&&Number(s.trust||0)>=42)return 2;if(days>=2)return 1;return 0}
function eligible(s:SaveLike){if(!s.metLucas||!s.official||s.screen!=='game'||document.hidden||blocked())return false;if(!lucasWorldPlace(s))return false;if(Boolean(s.flags.lucasAway)||Boolean(s.flags.corridaLive))return false;const t=mins(s.time);if(t<600||t>1320)return false;const stage=stageFor(s);if(stage===0)return false;if(Number(s.flags.marionLucasWorldStageShown||0)>=stage)return false;const last=Number(s.flags.marionLucasWorldLastDay||0);if(last&&s.day-last<2)return false;return true}
function sceneFor(s:SaveLike,stage:number){if(stage===1)return{tone:'noticed',k:'UN PETIT DÉTAIL',t:'Quelqu’un te salue avant de saluer Lucas.',b:'Rien de spectaculaire. Juste ton prénom prononcé naturellement, sans avoir besoin qu’il te présente encore une fois. Tu le remarques après coup.'};if(stage===2)return{tone:'codes',k:'TU CONNAIS DÉJÀ LE RYTHME',t:'Tu n’attends plus qu’on t’explique tout.',b:'Tu sais où te mettre quand le mouvement accélère, quand laisser Lucas travailler, quand revenir près de lui. Ce monde commence à perdre son côté étranger.'};if(stage===3)return{tone:'own',k:'PAS SEULEMENT « AVEC LUCAS »',t:'Une conversation continue même quand il s’éloigne.',b:'Pendant quelques minutes, personne ne te regarde comme une extension de lui. On te parle à toi. Et quand Lucas revient, tu étais déjà parfaitement à ta place.'};return{tone:'belong',k:'SANS L’AVOIR DÉCIDÉ',t:'Tu as tes propres repères ici.',b:'Tu reconnais les habitudes, certains visages te reconnaissent, tu sais où attendre et quand avancer. Lucas fait toujours partie de ce monde, mais tu n’y existes plus uniquement à travers lui.'}}
function show(s:SaveLike){if(active||!eligible(s))return;const stage=stageFor(s);const game=document.querySelector<HTMLElement>('main.game');if(!game)return;active=true;const e=sceneFor(s,stage);const card=document.createElement('aside');card.id='marionPlaceLucasWorld';card.className=`marionPlaceLucasWorld ${e.tone}`;card.innerHTML=`<span>${e.k}</span><strong>${e.t}</strong><small>${e.b}</small>`;game.appendChild(card);s.flags.marionLucasWorldStageShown=stage;s.flags.marionLucasWorldLastDay=s.day;s.flags.marionLucasWorldBelonging=true;if(stage>=3)s.trust=Number(s.trust||0)+1;if(stage===4)s.stress=Math.max(0,Number(s.stress||0)-1);if(stage===1)addMemory(s,'Dans le monde de Lucas, quelqu’un t’a saluée par ton prénom sans attendre qu’il te présente.');else if(stage===2)addMemory(s,'Tu as commencé à connaître les codes et le rythme autour du travail de Lucas.');else if(stage===3)addMemory(s,'Dans l’entourage de Lucas, une conversation a continué avec toi même quand il s’est éloigné.');else addMemory(s,'Le monde de Lucas a cessé d’être seulement le sien : tu y as désormais tes propres repères.');write(s);setTimeout(()=>card.classList.add('is-leaving'),6500);setTimeout(()=>{card.remove();active=false},8200)}
function arm(){const s=read();if(!s)return;if(s.screen==='game'&&s.metLucas&&s.official&&lucasWorldPlace(s))markExposure(s);const fresh=read();if(!fresh||!eligible(fresh)){if(timer)clearTimeout(timer);timer=0;return}if(active||timer)return;timer=window.setTimeout(()=>{timer=0;const f=read();if(f)show(f)},16000+((fresh.day*101+mins(fresh.time))%9000))}
window.addEventListener('storage',arm);document.addEventListener('visibilitychange',()=>{if(!document.hidden)arm()});window.setInterval(arm,16000);arm();console.info('[Life] Marion now gains her own place in Lucas world progressively');
