import './marionCoupleInitiativeDirector.css';

type SaveLike={day:number;time:string;place:string;screen:string;metLucas:boolean;official:boolean;relationship:number;trust:number;chemistry:number;energy:number;stress:number;memories:string[];flags:Record<string,boolean|number|string>;updatedAt:number};
const SAVE_KEY='marion-lucas-save-v4';
let active=false,timer=0;
function read():SaveLike|null{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null') as SaveLike|null}catch{return null}}
function write(s:SaveLike){s.updatedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(s))}
function mins(t:string){const [h,m]=String(t||'09:00').split(':').map(Number);return(h||0)*60+(m||0)}
function fmt(total:number){total=((total%1440)+1440)%1440;return`${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}
function addMemory(s:SaveLike,t:string){if(!Array.isArray(s.memories))s.memories=[];if(!s.memories.includes(t))s.memories.unshift(t);s.memories=s.memories.slice(0,190)}
function blocked(){return Boolean(document.querySelector('#overlay.open,.eventOverlay,.incomingCallOverlay,.moniaDramaScene,#moniaSceneOffer,.coupleIntimacyVeil,.postEventReunion,.marionCoupleInitiative'))}
function together(){return Boolean(document.querySelector('[data-world-action="together"],[data-world-action="horseRide"],[data-world-action="trainingVisit"]'))}
function eligible(s:SaveLike){if(!s.metLucas||!s.official||s.screen!=='game'||document.hidden||blocked()||!together())return false;if(Boolean(s.flags.lucasBusy)||Boolean(s.flags.lucasAway)||Boolean(s.flags.corridaLive)||Boolean(s.flags.lucasRoutineBusy))return false;if(Number(s.relationship||0)<44)return false;if(Number(s.flags.marionCoupleInitiativeDay||0)===s.day)return false;const last=Number(s.flags.marionCoupleInitiativeLastDay||0);if(last&&s.day-last<2)return false;if(Number(s.flags.lucasSharedRoutineDay||0)===s.day)return false;const t=mins(s.time);return t>=690&&t<=1260}
function sceneFor(s:SaveLike){const charged=Number(s.chemistry||0)>=42;const ownLife=Number(s.flags.marionOwnLifeLastDay||0)>=s.day-2;const k=(s.day*43+Math.round(s.relationship||0)+Math.round(s.trust||0))%5;if(s.place==='finca'||s.place==='estate')return charged?{tone:'finca',k:'CETTE FOIS, C’EST TOI',t:'Tu as envie de le tirer dehors deux minutes.',b:'Pas parce qu’il l’a proposé. Juste parce que tu as envie de ce moment avec lui.',a:'L’embarquer avec toi',c:'Garder l’idée pour plus tard',kind:'walk'}:{tone:'finca',k:'UNE IDÉE À TOI',t:'Tu lui proposes de sortir prendre l’air.',b:'Lucas lève les yeux vers toi, surpris une demi-seconde seulement, puis attrape ses clés sans poser de question.',a:'Y aller ensemble',c:'Changer d’avis',kind:'air'};if(s.place==='madrid')return{tone:'city',k:'TON TOUR',t:'Tu lui proposes de sortir sans programme.',b:ownLife?'Tu as passé du temps dans son monde. Là, c’est toi qui choisis le rythme : un café, quelques rues, rien d’organisé.':'Pas de rendez-vous prévu. Juste une idée qui te traverse et que tu lui lances.',a:'L’emmener avec toi',c:'Rester tranquille',kind:'city'};if(s.place==='family')return{tone:'family',k:'UNE PARENTHÈSE À TOI',t:'Tu lui fais signe de venir avec toi.',b:'La maison est pleine de voix. Cette fois, c’est toi qui voles cinq minutes au reste du monde.',a:'L’entraîner dehors',c:'Rester avec les autres',kind:'escape'};if(k===0)return{tone:'surprise',k:'SANS PRÉVENIR',t:'Tu décides de lui faire une petite surprise.',b:'Rien de spectaculaire : son café comme il l’aime, quelque chose à grignoter, ou juste cette attention qui dit que tu as pensé à lui.',a:'Le faire maintenant',c:'Plus tard',kind:'surprise'};if(k===1&&charged)return{tone:'charged',k:'TU PRENDS L’INITIATIVE',t:'Tu vas vers lui avant qu’il ne fasse le premier geste.',b:'Lucas comprend immédiatement. Son sourire change juste assez pour te faire regretter une seconde d’avoir attendu jusque-là.',a:'Aller jusqu’à lui',c:'Le faire attendre',kind:'close'};return{tone:'quiet',k:'UN MOMENT QUE TU CHOISIS',t:'Tu lui proposes simplement de rester avec toi.',b:'Pas besoin de sortie ni de grand plan. Tu veux sa présence, alors tu le lui dis.',a:'Le garder près de toi',c:'Continuer ta journée',kind:'quiet'}}
function resolve(s:SaveLike,accept:boolean,kind:string){s.flags.marionCoupleInitiativeDay=s.day;s.flags.marionCoupleInitiativeLastDay=s.day;s.flags.marionCoupleInitiativeKind=kind;s.flags.marionCoupleInitiativeChoice=accept?'yes':'later';if(accept){const duration=kind==='city'?34:kind==='walk'||kind==='air'?26:kind==='escape'?16:kind==='surprise'?14:20;s.time=fmt(mins(s.time)+duration);s.energy=Math.max(0,Number(s.energy||0)-1);s.stress=Math.max(0,Number(s.stress||0)-2);s.relationship=Number(s.relationship||0)+1;s.trust=Number(s.trust||0)+1;if(kind==='close'||kind==='walk')s.chemistry=Number(s.chemistry||0)+1;addMemory(s,'Cette fois, c’est toi qui as créé un moment à deux avec Lucas, sans attendre qu’il le propose.')}else addMemory(s,'Tu as eu envie de prendre l’initiative avec Lucas, puis tu as gardé ton propre rythme.');write(s)}
function show(s:SaveLike){if(active||!eligible(s))return;const game=document.querySelector<HTMLElement>('main.game');if(!game)return;active=true;const e=sceneFor(s);const veil=document.createElement('div');veil.id='marionCoupleInitiative';veil.className=`marionCoupleInitiative ${e.tone}`;veil.innerHTML=`<section><span>${e.k}</span><h2>${e.t}</h2><p>${e.b}</p><div><button id="marionInitYes" class="primary">${e.a}</button><button id="marionInitNo">${e.c}</button></div></section>`;game.appendChild(veil);const close=()=>{veil.classList.add('is-leaving');setTimeout(()=>{veil.remove();active=false},260)};(veil.querySelector('#marionInitYes') as HTMLButtonElement).onclick=()=>{const f=read();if(f)resolve(f,true,e.kind);close();setTimeout(()=>location.reload(),280)};(veil.querySelector('#marionInitNo') as HTMLButtonElement).onclick=()=>{const f=read();if(f)resolve(f,false,e.kind);close()}}
function arm(){const s=read();if(!s||!eligible(s)){if(timer)clearTimeout(timer);timer=0;return}if(active||timer)return;timer=window.setTimeout(()=>{timer=0;const f=read();if(f)show(f)},18000+((s.day*101+mins(s.time))%11000))}
window.addEventListener('storage',arm);document.addEventListener('visibilitychange',()=>{if(!document.hidden)arm()});window.setInterval(arm,15000);arm();console.info('[Marion] autonomous couple initiative opportunities active');