import './publicPrivateChemistryDirector.css';

type SaveLike={day:number;time:string;place:string;screen:string;metLucas:boolean;official:boolean;relationship:number;trust:number;chemistry:number;memories:string[];flags:Record<string,boolean|number|string>;updatedAt:number};
const SAVE_KEY='marion-lucas-save-v4';
let active=false,timer=0;
function read():SaveLike|null{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null') as SaveLike|null}catch{return null}}
function write(s:SaveLike){s.updatedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(s))}
function mins(t:string){const [h,m]=String(t||'09:00').split(':').map(Number);return(h||0)*60+(m||0)}
function addMemory(s:SaveLike,t:string){if(!Array.isArray(s.memories))s.memories=[];if(!s.memories.includes(t))s.memories.unshift(t);s.memories=s.memories.slice(0,120)}
function blocked(){return Boolean(document.querySelector('#overlay.open,.eventOverlay,.incomingCallOverlay,.moniaDramaScene,#moniaSceneOffer,.coupleIntimacyVeil,.publicPrivateChemistry'))}
function publicPlace(s:SaveLike){return['madrid','family','arenes','nimes','cafe','station'].includes(s.place)}
function eligible(s:SaveLike){if(!s.metLucas||!s.official||s.screen!=='game'||document.hidden||blocked())return false;if(!publicPlace(s))return false;if(Boolean(s.flags.lucasBusy)||Boolean(s.flags.lucasAway)||Boolean(s.flags.corridaLive))return false;if(Number(s.flags.publicPrivateChemistryDay||0)===s.day)return false;const t=mins(s.time);if(t<600||t>1320)return false;return Number(s.relationship||0)>=50&&Number(s.chemistry||0)>=36}
function copyFor(s:SaveLike){const recent=Number(s.flags.coupleMadeLoveDay||0)>=s.day-1;const k=(s.day*23+Math.round(s.chemistry||0)+Math.round(s.relationship||0))%5;if(s.place==='family')return['AU MILIEU DES AUTRES','Personne ne remarque rien.','Sous la table, les doigts de Lucas frôlent les tiens une seconde. Son visage, lui, ne change presque pas.'];if(recent&&k%2===0)return['COMME SI DE RIEN N’ÉTAIT','Il parle normalement avec les autres.','Quand son regard revient vers toi, une fraction de seconde suffit pour te rappeler exactement à quel point vous étiez seuls la veille.'];if(k===1)return['EN PASSANT','Lucas passe derrière toi.','Sa main effleure ta taille juste assez pour que le geste ressemble à un accident pour tout le monde sauf pour toi.'];if(k===2)return['UN REGARD DE TROP','Quelqu’un continue de parler à côté de vous.','Lucas écoute. Enfin, en théorie. Son regard s’attarde sur toi avant qu’il ne se reprenne.'];if(k===3)return['À QUELQUES CENTIMÈTRES','Vous vous retrouvez côte à côte un instant.','Il se penche pour te dire quelque chose à voix basse. La phrase est banale. La distance, beaucoup moins.'];return['RIEN DE VISIBLE','En public, Lucas reste parfaitement maître de lui.','C’est précisément pour ça que le bref contact de sa main contre la tienne semble beaucoup plus intime qu’il ne devrait.']}
function show(s:SaveLike){if(active||!eligible(s))return;const game=document.querySelector<HTMLElement>('main.game');if(!game)return;active=true;const [k,t,b]=copyFor(s);const card=document.createElement('aside');card.id='publicPrivateChemistry';card.className='publicPrivateChemistry';card.innerHTML=`<span>${k}</span><strong>${t}</strong><small>${b}</small>`;game.appendChild(card);s.flags.publicPrivateChemistryDay=s.day;s.flags.publicPrivateSpark=true;s.flags.publicPrivateSparkAt=mins(s.time);s.chemistry=Number(s.chemistry||0)+1;addMemory(s,'En public, un geste presque invisible de Lucas a rendu votre intimité encore plus présente.');write(s);setTimeout(()=>card.classList.add('is-leaving'),5600);setTimeout(()=>{card.remove();active=false},7200)}
function arm(){const s=read();if(!s||!eligible(s)){if(timer)clearTimeout(timer);timer=0;return}if(active||timer)return;timer=window.setTimeout(()=>{timer=0;const f=read();if(f)show(f)},18000+((s.day*61+mins(s.time))%9000))}
window.addEventListener('storage',arm);document.addEventListener('visibilitychange',()=>{if(!document.hidden)arm()});window.setInterval(arm,12000);arm();console.info('[Romance] public/private chemistry contrast active');
