import './socialFreedom.css';
import './monia/living-social-runtime';
import {getLucasCommunicationPolicy} from './monia/lucas-presence-engine';

const SAVE_KEY='marion-lucas-save-v4';
type SaveLike={day?:number;time?:string;metLucas?:boolean;messages?:Array<{from:string;text:string;day:number;read:boolean}>;memories?:string[];flags?:Record<string,boolean|number|string>;updatedAt?:number};
type Contact={id:'marine'|'lucas';name:string;subtitle:string;video:boolean};
let callTimer=0,callClock=0,connectedAt=0,currentKind:'call'|'visio'|''='',currentWho='';

function read():SaveLike{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'{}') as SaveLike}catch{return {}}}
function write(s:SaveLike){s.updatedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('marion:statechange',{detail:{source:'social'}}))}
function flags(s:SaveLike){if(!s.flags)s.flags={};return s.flags}
function phone(){return document.querySelector<HTMLElement>('.phoneDevice')}
function content(){return document.querySelector<HTMLElement>('.phoneDevice #phoneContent')}
function safe(v:string){return v.replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c))}
function isSocialApp(el:HTMLElement){const label=(el.querySelector('span')?.textContent||el.textContent||'').toLowerCase();return label.includes('appel')||label.includes('contact')}
function clearTimers(){if(callTimer)window.clearTimeout(callTimer);if(callClock)window.clearInterval(callClock);callTimer=0;callClock=0}
function availableContacts(s:SaveLike):Contact[]{const out:Contact[]=[{id:'marine',name:'Marine',subtitle:'Amie · Nîmes',video:false}];if(s.metLucas)out.push({id:'lucas',name:'Lucas',subtitle:'Contact important',video:true});return out}
function contactById(s:SaveLike,id:string){return availableContacts(s).find(c=>c.id===id)||availableContacts(s)[0]}
function formatDuration(ms:number){const total=Math.max(0,Math.floor(ms/1000)),m=Math.floor(total/60),sec=String(total%60).padStart(2,'0');return `${m}:${sec}`}
function addMemory(s:SaveLike,text:string){if(!Array.isArray(s.memories))s.memories=[];if(!s.memories.includes(text))s.memories.unshift(text);s.memories=s.memories.slice(0,60)}
function stamp(s:SaveLike){const [h,m]=String(s.time||'12:00').split(':').map(Number);return Number(s.day||1)*1440+(h||0)*60+(m||0)}
function history(s:SaveLike,who?:string){return String(flags(s).socialCallHistory||'').split('§').filter(Boolean).map(x=>{const [person,day,time,kind,state,duration]=x.split('|');return{person,day,time,kind,state,duration}}).filter(x=>!who||x.person===who).slice(0,12)}
function addHistory(s:SaveLike,who:string,kind:string,state:string,duration=0){const f=flags(s),entry=`${who}|${Number(s.day||1)}|${String(s.time||'--:--')}|${kind}|${state}|${duration}`;f.socialCallHistory=[entry,...String(f.socialCallHistory||'').split('§').filter(Boolean)].slice(0,30).join('§')}
function lastContactState(s:SaveLike,who:string){const h=history(s,who)[0];if(!h)return'Aucun appel récent';const map:Record<string,string>={ended:'Appel terminé',connected:'Appel connecté',cancelled:'Appel annulé',started:'Appel lancé',missed:'Sans réponse',unreachable:'Injoignable',local:'Présent avec toi'};return `${map[h.state]||'Appel'} · Jour ${h.day}`}
function lucasStatus(){return getLucasCommunicationPolicy()}

function renderContacts(){clearTimers();connectedAt=0;currentKind='';currentWho='';const p=phone(),c=content();if(!p||!c)return;const s=read();p.classList.add('isSocialOpen');p.classList.remove('isMessagesOpen');const contacts=availableContacts(s);c.className='socialFreedomPanel';c.innerHTML=`<div class="socialFreedomHead"><button type="button" data-social-back aria-label="Retour">‹</button><div><small>CONTACTS</small><strong>Contacts importants</strong></div></div><div class="socialContactList">${contacts.map(x=>`<button type="button" class="socialContact socialContactRow" data-social-profile="${x.id}"><i>${safe(x.name.slice(0,1))}</i><div><strong>${safe(x.name)}</strong><small>${safe(x.subtitle)}</small><em>${safe(lastContactState(s,x.id))}</em></div><span>›</span></button>`).join('')}</div><p class="socialHint">Messages, appels et historique restent séparés pour chaque personne.</p>`}
}

function renderProfile(who:string){clearTimers();connectedAt=0;currentKind='';currentWho='';const p=phone(),c=content();if(!p||!c)return;const s=read(),person=contactById(s,who);p.classList.add('isSocialOpen');p.classList.remove('isMessagesOpen');const rows=history(s,person.id).slice(0,6);const labels:Record<string,string>={call:'Appel',visio:'Visio'},states:Record<string,string>={ended:'Terminé',connected:'Connecté',cancelled:'Annulé',started:'Lancé',missed:'Sans réponse',unreachable:'Injoignable',local:'Avec toi'};const availability=person.id==='lucas'?lucasStatus():null;c.className='socialFreedomPanel socialProfilePanel';c.innerHTML=`<div class="socialFreedomHead"><button type="button" data-social-contacts aria-label="Retour">‹</button><div><small>CONTACT</small><strong>${safe(person.name)}</strong></div></div><section class="socialProfileHero"><i>${safe(person.name.slice(0,1))}</i><h3>${safe(person.name)}</h3><p>${safe(person.subtitle)}</p>${availability?`<small>${safe(availability.label)}</small>`:''}<div><button type="button" data-social-message="${person.id}">Message</button><button type="button" data-social-call="${person.id}">Appeler</button>${person.video?`<button type="button" class="isDisabled" data-social-video-disabled title="Aucun clip visio approuvé">Visio</button>`:''}</div></section><section class="socialHistory"><span>HISTORIQUE</span>${rows.length?rows.map(r=>`<article><i>${r.kind==='visio'?'◉':'☎'}</i><div><strong>${labels[r.kind]||'Appel'}</strong><small>Jour ${safe(r.day)} · ${safe(r.time)}</small></div><em>${states[r.state]||safe(r.state)}</em></article>`).join(''):'<p>Aucun appel récent avec cette personne.</p>'}</section>${person.video?'<p class="socialVisioNote">Visio disponible uniquement lorsqu’un clip Lucas est explicitement validé pour cet usage.</p>':''}`}
}

function recordSocialAction(kind:string,who:string,outcome='started'){const s=read(),f=flags(s);const key=`social_${kind}_${who}_count`;f[key]=Number(f[key]||0)+1;f.lastFreeSocialAction=`${kind}:${who}`;f.lastFreeSocialOutcome=outcome;f.lastFreeSocialAt=Date.now();addHistory(s,who,kind,outcome);write(s)}
function updateOutcome(kind:string,who:string,outcome:string,duration=0){const s=read(),f=flags(s);f.lastFreeSocialAction=`${kind}:${who}`;f.lastFreeSocialOutcome=outcome;f.lastFreeSocialAt=Date.now();f[`social_${kind}_${who}_lastOutcome`]=outcome;addHistory(s,who,kind,outcome,duration);write(s)}
function commitInitiative(kind:string,who:string,durationMs:number){const s=read(),f=flags(s);const seconds=Math.max(0,Math.floor(durationMs/1000));f.socialInitiativeSerial=Number(f.socialInitiativeSerial||0)+1;f.socialInitiativePending=`${kind}:${who}`;f.socialInitiativeDuration=seconds;f.socialInitiativeDay=Number(s.day||1);f.socialInitiativeAt=Date.now();f.lastFreeSocialOutcome='ended';addMemory(s,`Tu as pris l’initiative de ${kind==='visio'?'lancer une visio avec':'appeler'} ${who==='lucas'?'Lucas':'Marine'}.`);write(s)}
function queueLucasFollowup(delay:number,reason:string){const s=read(),f=flags(s);f.lucasCallbackDueStamp=stamp(s)+Math.max(20,delay);f.lucasCallbackReason=reason;f.lucasCallbackPending=true;write(s)}
function resolveLucasFollowup(){const s=read(),f=flags(s);if(f.lucasCallbackPending!==true||Number(f.lucasCallbackDueStamp||0)>stamp(s))return;const policy=lucasStatus();if(policy.mode==='local'||policy.mode==='missed'||policy.mode==='unreachable')return;if(!Array.isArray(s.messages))s.messages=[];const text='Je viens de voir ton appel. J’étais pris. Ça va ?';if(!s.messages.some(m=>m.from==='Lucas'&&m.day===Number(s.day||1)&&m.text===text)){s.messages.unshift({from:'Lucas',text,day:Number(s.day||1),read:false});f.phoneToast=`Lucas|${text}`;f.phoneToastAt=stamp(s)}delete f.lucasCallbackPending;delete f.lucasCallbackDueStamp;delete f.lucasCallbackReason;write(s)}

function connectCall(who:string){const c=content();if(!c)return;const status=c.querySelector<HTMLElement>('[data-call-status]');if(status)status.textContent='connecté';connectedAt=Date.now();currentKind='call';currentWho=who;updateOutcome('call',who,'connected');const duration=c.querySelector<HTMLElement>('[data-call-duration]');if(duration){duration.hidden=false;duration.textContent='0:00';callClock=window.setInterval(()=>{duration.textContent=formatDuration(Date.now()-connectedAt)},1000)}}
function showCall(who:string){clearTimers();connectedAt=0;currentKind='call';currentWho=who;const p=phone(),c=content();if(!p||!c)return;const s=read(),person=contactById(s,who);p.classList.add('isSocialOpen');c.className='socialFreedomPanel socialCallScreen';
  if(person.id==='lucas'){
    const policy=lucasStatus();
    if(policy.mode==='local'){recordSocialAction('call','lucas','local');c.innerHTML=`<div class="socialCallAvatar">L</div><small>PRÉSENCE</small><strong>Lucas</strong><span data-call-status>Il est avec toi.</span><div class="socialCallActions"><button type="button" data-social-end>Retour</button></div>`;return}
    if(policy.mode==='unreachable'){recordSocialAction('call','lucas','unreachable');c.innerHTML=`<div class="socialCallAvatar">L</div><small>APPEL</small><strong>Lucas</strong><span data-call-status>momentanément injoignable</span><div class="socialCallActions"><button type="button" data-social-end>Retour</button></div>`;queueLucasFollowup(policy.responseDelayMinutes,policy.reason);return}
    if(policy.mode==='missed'){recordSocialAction('call','lucas','started');c.innerHTML=`<div class="socialCallAvatar">L</div><small>APPEL</small><strong>Lucas</strong><span data-call-status>sonnerie…</span><div class="socialCallActions"><button type="button" data-social-end>Raccrocher</button></div>`;callTimer=window.setTimeout(()=>{const status=c.querySelector<HTMLElement>('[data-call-status]');if(status)status.textContent='pas de réponse';updateOutcome('call','lucas','missed');queueLucasFollowup(policy.responseDelayMinutes,policy.reason)},2400);return}
  }
  recordSocialAction('call',person.id);c.innerHTML=`<div class="socialCallAvatar">${safe(person.name.slice(0,1))}</div><small>APPEL</small><strong>${safe(person.name)}</strong><span data-call-status>sonnerie…</span><span class="socialCallDuration" data-call-duration hidden>0:00</span><div class="socialCallActions"><button type="button" data-social-speaker>Haut-parleur</button><button type="button" data-social-end>Raccrocher</button></div>`;callTimer=window.setTimeout(()=>connectCall(person.id),1100)
}

function endCurrentSocial(){const c=content();if(!c)return;const kind=currentKind||'call',who=currentWho||'marine',duration=connectedAt?Date.now()-connectedAt:0;if(connectedAt){updateOutcome(kind,who,'ended',Math.floor(duration/1000));commitInitiative(kind,who,duration)}else if(flags(read()).lastFreeSocialOutcome==='started')updateOutcome(kind,who,'cancelled');clearTimers();connectedAt=0;renderProfile(who)}
function closeSocial(){clearTimers();connectedAt=0;currentKind='';currentWho='';const p=phone();p?.classList.remove('isSocialOpen');const c=content();if(c)c.className='';window.dispatchEvent(new CustomEvent('marion:phone-refresh'));window.dispatchEvent(new CustomEvent('marion:statechange',{detail:{source:'social-close'}}))}
function openMessagesFor(who:string){const p=phone();p?.classList.remove('isSocialOpen');const c=content();if(c)c.className='';const messages=[...document.querySelectorAll<HTMLButtonElement>('.phoneDevice [data-phoneapp="messages"]')][0];messages?.click();window.setTimeout(()=>{const name=who==='lucas'?'Lucas':'Marine';document.querySelector<HTMLButtonElement>(`.phoneDevice [data-native-thread="${name}"]`)?.click()},180)}

document.addEventListener('click',e=>{const t=e.target as HTMLElement|null;if(!t)return;const app=t.closest<HTMLElement>('.phoneDevice .nativeApp');if(app&&isSocialApp(app)){e.preventDefault();e.stopPropagation();renderContacts();return}const profile=t.closest<HTMLElement>('[data-social-profile]');if(profile){e.preventDefault();renderProfile(profile.dataset.socialProfile||'marine');return}if(t.closest('[data-social-contacts]')){e.preventDefault();renderContacts();return}const msg=t.closest<HTMLElement>('[data-social-message]');if(msg){e.preventDefault();openMessagesFor(msg.dataset.socialMessage||'marine');return}const call=t.closest<HTMLElement>('[data-social-call]');if(call){e.preventDefault();showCall(call.dataset.socialCall||'marine');return}if(t.closest('[data-social-video-disabled]')){e.preventDefault();return}if(t.closest('[data-social-back]')){e.preventDefault();closeSocial();return}if(t.closest('[data-social-end]')){e.preventDefault();endCurrentSocial();return}if(t.closest('[data-social-speaker]')){t.closest<HTMLButtonElement>('button')?.classList.toggle('isActive');return}},{capture:true});
window.addEventListener('pagehide',clearTimers);window.addEventListener('marion:statechange',resolveLucasFollowup as EventListener);window.setInterval(resolveLucasFollowup,5000);resolveLucasFollowup();
console.info('[Social] Lucas calls now follow canonical presence, work and travel availability');
