import './socialFreedom.css';

const SAVE_KEY='marion-lucas-save-v4';
const LUCAS_VISIO_FALLBACK='/resources/monia/generated/intro-lucas-candidate-desktop.mp4';
type SaveLike={day?:number;time?:string;metLucas?:boolean;messages?:Array<{from:string;text:string;day:number;read:boolean}>;flags?:Record<string,boolean|number|string>;updatedAt?:number};
type Contact={id:'marine'|'lucas';name:string;subtitle:string;video:boolean};
let callTimer=0,callClock=0,connectedAt=0;

function read():SaveLike{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'{}') as SaveLike}catch{return {}}}
function write(s:SaveLike){s.updatedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(s));window.dispatchEvent(new CustomEvent('marion:statechange',{detail:{source:'social'}}))}
function flags(s:SaveLike){if(!s.flags)s.flags={};return s.flags}
function phone(){return document.querySelector<HTMLElement>('.phoneDevice')}
function content(){return document.querySelector<HTMLElement>('.phoneDevice #phoneContent')}
function safe(v:string){return v.replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c))}
function isSocialApp(el:HTMLElement){const label=(el.querySelector('span')?.textContent||el.textContent||'').toLowerCase();return label.includes('appel')||label.includes('contact')}
function clearTimers(){if(callTimer)window.clearTimeout(callTimer);if(callClock)window.clearInterval(callClock);callTimer=0;callClock=0;connectedAt=0}
function availableContacts(s:SaveLike):Contact[]{const out:Contact[]=[{id:'marine',name:'Marine',subtitle:'Disponible dans tes contacts',video:false}];if(s.metLucas)out.push({id:'lucas',name:'Lucas',subtitle:'Appel ou visio',video:true});return out}
function formatDuration(ms:number){const total=Math.max(0,Math.floor(ms/1000)),m=Math.floor(total/60),sec=String(total%60).padStart(2,'0');return `${m}:${sec}`}

function renderContacts(){clearTimers();const p=phone(),c=content();if(!p||!c)return;const s=read();p.classList.add('isSocialOpen');p.classList.remove('isMessagesOpen');const contacts=availableContacts(s);c.className='socialFreedomPanel';c.innerHTML=`<div class="socialFreedomHead"><button type="button" data-social-back aria-label="Retour">‹</button><div><small>CONTACTS</small><strong>Qui veux-tu appeler ?</strong></div></div><div class="socialContactList">${contacts.map(x=>`<article class="socialContact"><i>${safe(x.name.slice(0,1))}</i><div><strong>${safe(x.name)}</strong><small>${safe(x.subtitle)}</small></div><button type="button" data-social-call="${x.id}" aria-label="Appeler ${safe(x.name)}">Appeler</button>${x.video?`<button type="button" data-social-video="${x.id}" aria-label="Appeler ${safe(x.name)} en visio">Visio</button>`:''}</article>`).join('')}</div><p class="socialHint">Tu peux appeler quand tu veux. Le jeu garde l’initiative en mémoire et peut faire évoluer la suite autour de ce que tu fais.</p>`}
}

function recordSocialAction(kind:string,who:string,outcome='started'){const s=read(),f=flags(s);const key=`social_${kind}_${who}_count`;f[key]=Number(f[key]||0)+1;f.lastFreeSocialAction=`${kind}:${who}`;f.lastFreeSocialOutcome=outcome;f.lastFreeSocialAt=Date.now();write(s)}
function updateOutcome(kind:string,who:string,outcome:string){const s=read(),f=flags(s);f.lastFreeSocialAction=`${kind}:${who}`;f.lastFreeSocialOutcome=outcome;f.lastFreeSocialAt=Date.now();f[`social_${kind}_${who}_lastOutcome`]=outcome;write(s)}

function connectCall(who:string){const c=content();if(!c)return;const status=c.querySelector<HTMLElement>('[data-call-status]');if(status)status.textContent='connecté';connectedAt=Date.now();updateOutcome('call',who,'connected');const duration=c.querySelector<HTMLElement>('[data-call-duration]');if(duration){duration.hidden=false;duration.textContent='0:00';callClock=window.setInterval(()=>{duration.textContent=formatDuration(Date.now()-connectedAt)},1000)}}
function showCall(who:string){clearTimers();const p=phone(),c=content();if(!p||!c)return;recordSocialAction('call',who);const name=who==='lucas'?'Lucas':'Marine';p.classList.add('isSocialOpen');c.className='socialFreedomPanel socialCallScreen';c.innerHTML=`<div class="socialCallAvatar">${safe(name.slice(0,1))}</div><small>APPEL</small><strong>${safe(name)}</strong><span data-call-status>sonnerie…</span><span class="socialCallDuration" data-call-duration hidden>0:00</span><div class="socialCallActions"><button type="button" data-social-speaker>Haut-parleur</button><button type="button" data-social-end>Raccrocher</button></div>`;callTimer=window.setTimeout(()=>connectCall(who),1100)}

function showLucasVisio(){clearTimers();const p=phone(),c=content();if(!p||!c)return;const s=read();if(!s.metLucas)return;recordSocialAction('visio','lucas');p.classList.add('isSocialOpen');c.className='socialFreedomPanel socialVideoScreen';c.innerHTML=`<video class="socialVideo" src="${LUCAS_VISIO_FALLBACK}" autoplay muted loop playsinline preload="metadata"></video><div class="socialVideoShade"></div><div class="socialVideoTop"><small>VISIO</small><strong>Lucas</strong><span data-visio-status>connexion…</span></div><div class="socialVideoControls"><button type="button" data-social-mute>Micro</button><button type="button" data-social-camera>Caméra</button><button type="button" data-social-end>Raccrocher</button></div>`;callTimer=window.setTimeout(()=>{const status=c.querySelector<HTMLElement>('[data-visio-status]');if(status)status.textContent='connecté';updateOutcome('visio','lucas','connected')},900)}

function endCurrentSocial(){const c=content();const p=phone();if(!c||!p)return;const wasVideo=c.classList.contains('socialVideoScreen');const who=(c.querySelector('strong')?.textContent||'').toLowerCase().includes('lucas')?'lucas':'marine';if(connectedAt)updateOutcome('call',who,'ended');else if(wasVideo)updateOutcome('visio',who,'ended');clearTimers();renderContacts()}
function closeSocial(){clearTimers();const p=phone();p?.classList.remove('isSocialOpen');const c=content();if(c)c.className='';window.dispatchEvent(new CustomEvent('marion:phone-refresh'));window.dispatchEvent(new CustomEvent('marion:statechange',{detail:{source:'social-close'}}))}

document.addEventListener('click',e=>{const t=e.target as HTMLElement|null;if(!t)return;const app=t.closest<HTMLElement>('.phoneDevice .nativeApp');if(app&&isSocialApp(app)){e.preventDefault();e.stopPropagation();renderContacts();return}const call=t.closest<HTMLElement>('[data-social-call]');if(call){e.preventDefault();showCall(call.dataset.socialCall||'marine');return}const video=t.closest<HTMLElement>('[data-social-video]');if(video){e.preventDefault();if(video.dataset.socialVideo==='lucas')showLucasVisio();return}if(t.closest('[data-social-back]')){e.preventDefault();closeSocial();return}if(t.closest('[data-social-end]')){e.preventDefault();endCurrentSocial();return}if(t.closest('[data-social-mute]')){const v=document.querySelector<HTMLVideoElement>('.socialVideo');if(v){v.muted=!v.muted;t.closest<HTMLButtonElement>('button')?.classList.toggle('isActive',!v.muted)}return}if(t.closest('[data-social-camera]')){t.closest<HTMLButtonElement>('button')?.classList.toggle('isActive');return}if(t.closest('[data-social-speaker]')){t.closest<HTMLButtonElement>('button')?.classList.toggle('isActive');return}},{capture:true});
window.addEventListener('pagehide',clearTimers);
console.info('[Social] free calls have realistic ringing, connection state and remembered outcomes');
