import './travelSocialOrbitDirector.css';

type CalendarItem={owner:'Marion'|'Lucas'|'Nous';title:string;day:number;note:string};
type SaveLike={day:number;time:string;place:string;screen:string;metLucas:boolean;official:boolean;relationship:number;trust:number;chemistry:number;stress:number;calendar:CalendarItem[];memories:string[];flags:Record<string,boolean|number|string>;updatedAt:number};
const SAVE_KEY='marion-lucas-save-v4';
let active=false,timer=0;
function read():SaveLike|null{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null') as SaveLike|null}catch{return null}}
function write(s:SaveLike){s.updatedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(s))}
function mins(t:string){const [h,m]=String(t||'09:00').split(':').map(Number);return(h||0)*60+(m||0)}
function addMemory(s:SaveLike,t:string){if(!Array.isArray(s.memories))s.memories=[];if(!s.memories.includes(t))s.memories.unshift(t);s.memories=s.memories.slice(0,170)}
function blocked(){return Boolean(document.querySelector('#overlay.open,.eventOverlay,.incomingCallOverlay,.moniaDramaScene,#moniaSceneOffer,.coupleIntimacyVeil,.postEventReunion,.travelWithLucas,.travelSocialOrbit'))}
function isTravel(item:CalendarItem){const x=`${item.title||''} ${item.note||''}`.toLowerCase();return /(voyage|déplac|deplac|train|avion|vol|gare|aéroport|aeroport|route|hôtel|hotel|corrida|gala|presse|interview|réception|reception)/.test(x)}
function contextItem(s:SaveLike){return (Array.isArray(s.calendar)?s.calendar:[]).filter(i=>(i.owner==='Lucas'||i.owner==='Nous')&&i.day===s.day&&isTravel(i))[0]||null}
function publicEnough(s:SaveLike){return['station','madrid','family','arenes','nimes','cafe'].includes(s.place)}
function eligible(s:SaveLike){if(!s.metLucas||!s.official||s.screen!=='game'||document.hidden||blocked())return false;if(!contextItem(s))return false;if(!publicEnough(s))return false;if(Boolean(s.flags.lucasAway)||Boolean(s.flags.corridaLive))return false;if(Number(s.flags.travelSocialOrbitDay||0)===s.day)return false;const t=mins(s.time);return t>=720&&t<=1350}
function sceneFor(s:SaveLike){const recentPrivate=Number(s.flags.coupleMadeLoveDay||0)>=s.day-1;const close=Number(s.relationship||0)>=64;const k=(s.day*31+Math.round(s.relationship||0)+Math.round(s.trust||0))%5;if(s.place==='family')return{tone:'family',k:'DANS SON MONDE',t:'La conversation tourne autour de lui.',b:'Les habitudes, les prénoms, les références vont vite. Par moments tu te sens encore un peu nouvelle dans ce décor. Puis Lucas cherche ton regard au milieu d’une phrase, juste pour te raccrocher au sien.'};if(k===0)return{tone:'crowd',k:'AUTOUR DE LUI',t:'Les gens entrent et sortent sans vraiment prévenir.',b:close?'On lui parle, on l’arrête, on lui tend un téléphone. Entre deux échanges, Lucas pose brièvement sa main dans ton dos comme pour te remettre dans son axe.':'Son entourage connaît déjà le rythme. Toi, tu l’apprends encore : les conversations rapides, les attentes, les moments où tout repart sans prévenir.'};if(k===1)return{tone:'meal',k:'À TABLE',t:'Le repas s’étire plus que prévu.',b:'Quelqu’un raconte une anecdote, un autre parle déjà du lendemain. Lucas participe, puis pousse discrètement son verre vers toi pour te faire goûter, comme si cette petite complicité suffisait à faire une bulle au milieu du bruit.'};if(k===2&&recentPrivate)return{tone:'secret',k:'COMME SI DE RIEN N’ÉTAIT',t:'Personne autour de vous ne voit la différence.',b:'Lucas garde exactement le même visage avec les autres. Mais quand il croise ton regard, une seconde suffit pour te rappeler la version de lui que personne ici ne connaît vraiment.'};if(k===3)return{tone:'outside',k:'UNE MINUTE DEHORS',t:'Lucas s’éclipse du groupe.',b:'Il ne fait pas un grand geste. Il te fait juste signe de venir avec lui quelques mètres plus loin, le temps de retrouver du silence avant de retourner vers les autres.'};return{tone:'anchor',k:'AU MILIEU DU MOUVEMENT',t:'Tu commences à comprendre comment il te garde près de lui.',b:'Pas en restant collé à toi. Plutôt par une place laissée à côté de lui, un regard avant de changer de pièce, une main rapide au passage. Des petits repères dans un monde qui bouge beaucoup.'}}
function show(s:SaveLike){if(active||!eligible(s))return;const game=document.querySelector<HTMLElement>('main.game');if(!game)return;active=true;const e=sceneFor(s);const card=document.createElement('aside');card.id='travelSocialOrbit';card.className=`travelSocialOrbit ${e.tone}`;card.innerHTML=`<span>${e.k}</span><strong>${e.t}</strong><small>${e.b}</small>`;game.appendChild(card);s.flags.travelSocialOrbitDay=s.day;s.flags.travelSocialOrbitTone=e.tone;if(e.tone==='family'||e.tone==='anchor')s.trust=Number(s.trust||0)+1;if(e.tone==='secret')s.chemistry=Number(s.chemistry||0)+1;addMemory(s,'En déplacement, tu as commencé à trouver ta place dans le monde social de Lucas sans cesser d’être simplement toi.');write(s);setTimeout(()=>card.classList.add('is-leaving'),6200);setTimeout(()=>{card.remove();active=false},7900)}
function arm(){const s=read();if(!s||!eligible(s)){if(timer)clearTimeout(timer);timer=0;return}if(active||timer)return;timer=window.setTimeout(()=>{timer=0;const f=read();if(f)show(f)},14000+((s.day*89+mins(s.time))%8000))}
window.addEventListener('storage',arm);document.addEventListener('visibilitychange',()=>{if(!document.hidden)arm()});window.setInterval(arm,15000);arm();console.info('[Romance] travel social orbit active without inventing entourage canon');