import './travelWithLucasDirector.css';

type CalendarItem={owner:'Marion'|'Lucas'|'Nous';title:string;day:number;note:string};
type SaveLike={day:number;time:string;place:string;lastPlace?:string;screen:string;metLucas:boolean;official:boolean;relationship:number;trust:number;chemistry:number;stress:number;energy:number;calendar:CalendarItem[];memories:string[];flags:Record<string,boolean|number|string>;updatedAt:number};
const SAVE_KEY='marion-lucas-save-v4';
let active=false,timer=0;
function read():SaveLike|null{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null') as SaveLike|null}catch{return null}}
function write(s:SaveLike){s.updatedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(s))}
function mins(t:string){const [h,m]=String(t||'09:00').split(':').map(Number);return(h||0)*60+(m||0)}
function addMemory(s:SaveLike,t:string){if(!Array.isArray(s.memories))s.memories=[];if(!s.memories.includes(t))s.memories.unshift(t);s.memories=s.memories.slice(0,160)}
function blocked(){return Boolean(document.querySelector('#overlay.open,.eventOverlay,.incomingCallOverlay,.moniaDramaScene,#moniaSceneOffer,.coupleIntimacyVeil,.postEventReunion,.travelWithLucas'))}
function isTravel(item:CalendarItem){const x=`${item.title||''} ${item.note||''}`.toLowerCase();return /(voyage|déplac|deplac|train|avion|vol|gare|aéroport|aeroport|route|hôtel|hotel)/.test(x)}
function travelItem(s:SaveLike){return (Array.isArray(s.calendar)?s.calendar:[]).filter(i=>(i.owner==='Lucas'||i.owner==='Nous')&&(i.day===s.day||i.day===s.day+1)&&isTravel(i)).sort((a,b)=>a.day-b.day)[0]||null}
function hasHotel(item:CalendarItem|null){const x=`${item?.title||''} ${item?.note||''}`.toLowerCase();return /hôtel|hotel|chambre/.test(x)}
function stageFor(s:SaveLike,item:CalendarItem){const t=mins(s.time);if(item.day===s.day+1)return'prepare';if(s.place==='station')return'depart';if(Boolean(s.flags.lucasAway))return'transit';if(hasHotel(item)&&t>=1020)return'hotel';if(['madrid','finca','estate','family'].includes(s.place)&&String(s.lastPlace||'')!==s.place)return'arrive';if(t>=1050)return'arrive';return'transit'}
function eligible(s:SaveLike){if(!s.metLucas||!s.official||s.screen!=='game'||document.hidden||blocked())return false;const item=travelItem(s);if(!item)return false;const stage=stageFor(s,item);if(Boolean(s.flags[`travelLucas_${s.day}_${stage}`]))return false;if(Number(s.flags.travelLucasCuesDay||0)===s.day&&Number(s.flags.travelLucasCueCount||0)>=2)return false;return mins(s.time)>=420&&mins(s.time)<=1380}
function copyFor(s:SaveLike,item:CalendarItem,stage:string){const close=Number(s.relationship||0)>=64;const charged=Number(s.chemistry||0)>=46;if(stage==='prepare')return{tone:'prepare',k:'LA VEILLE',t:'Le voyage commence avant le départ.',b:'Un sac reste ouvert, les horaires reviennent dans la conversation, Lucas vérifie deux fois ce qu’il emporte. Votre journée se découpe déjà autour de demain.'};if(stage==='depart')return{tone:'depart',k:'EN ROUTE',t:'Vous avancez entre les horaires et les sacs.',b:close?'Au milieu du mouvement, Lucas trouve quand même une seconde pour poser sa main dans ton dos. Un geste bref, presque domestique, au milieu du départ.':'Le départ impose son rythme. Vous vous parlez par petites phrases entre deux vérifications, sans avoir besoin de remplir tous les silences.'};if(stage==='transit')return{tone:'transit',k:'ENTRE DEUX ENDROITS',t:'La journée n’appartient à aucun lieu.',b:charged?'Vous êtes assis côte à côte, fatigués par le trajet. Par moments vos épaules se touchent, et ce contact minuscule suffit à rendre l’attente beaucoup moins neutre.':'Le trajet morcelle tout : messages, sommeil léger, horaires, cafés pris trop vite. Votre couple existe aussi dans ces heures sans décor fixe.'};if(stage==='hotel')return{tone:'hotel',k:'UNE CHAMBRE QUI N’EST PAS LA VÔTRE',t:'Pour quelques heures, c’est ici.',b:close?'Les sacs tombent près de la porte. Lucas ferme enfin son téléphone et la pièce inconnue devient étrangement intime dès que vous vous retrouvez seuls.':'La chambre est impersonnelle, provisoire. Puis vos affaires commencent à occuper deux coins de la pièce, et elle paraît déjà un peu moins étrangère.'};return{tone:'arrive',k:'ARRIVÉS',t:'Le rythme retombe enfin.',b:charged?'Il y a toujours ce petit flottement après un trajet : le silence, les sacs encore fermés, puis Lucas qui te regarde comme s’il venait seulement maintenant de réaliser que vous êtes enfin seuls.':'Les horaires cessent enfin de commander. Vous posez les affaires, reprenez vos repères et laissez le nouveau lieu devenir juste le décor de la suite.'}}
function show(s:SaveLike){if(active||!eligible(s))return;const item=travelItem(s);if(!item)return;const stage=stageFor(s,item);const game=document.querySelector<HTMLElement>('main.game');if(!game)return;active=true;const e=copyFor(s,item,stage);const card=document.createElement('aside');card.id='travelWithLucas';card.className=`travelWithLucas ${e.tone}`;card.innerHTML=`<span>${e.k}</span><strong>${e.t}</strong><small>${e.b}</small>`;game.appendChild(card);s.flags[`travelLucas_${s.day}_${stage}`]=true;if(Number(s.flags.travelLucasCuesDay||0)!==s.day){s.flags.travelLucasCuesDay=s.day;s.flags.travelLucasCueCount=0}s.flags.travelLucasCueCount=Number(s.flags.travelLucasCueCount||0)+1;s.flags.travelLucasLastStage=stage;if(stage==='hotel')addMemory(s,'Un déplacement avec Lucas a transformé une chambre provisoire en parenthèse intime sans que le lieu ait d’importance.');else if(stage==='transit')addMemory(s,'Vous avez partagé ces heures étranges d’un voyage où la vie se déroule entre deux endroits.');else if(stage==='arrive')addMemory(s,'Après un déplacement, vous avez retrouvé votre rythme à deux avant même de vraiment vous installer.');write(s);setTimeout(()=>card.classList.add('is-leaving'),6200);setTimeout(()=>{card.remove();active=false},7900)}
function arm(){const s=read();if(!s||!eligible(s)){if(timer)clearTimeout(timer);timer=0;return}if(active||timer)return;timer=window.setTimeout(()=>{timer=0;const f=read();if(f)show(f)},11000+((s.day*79+mins(s.time))%7000))}
window.addEventListener('storage',arm);document.addEventListener('visibilitychange',()=>{if(!document.hidden)arm()});window.setInterval(arm,13000);arm();console.info('[Romance] travel-with-Lucas rhythm active without inventing travel canon');
